### ISSUE TITLE
[Feature Request] Mode `interaction_mode` is a confusing naming convention

### ISSUE THREAD

**Issue by matteobettini** [pytorch/rl#1016]
The default `interaction_mode` of probabilistic modules is `mode`, this is a bit confusing as it overloads the term mode in the same sentence.

Furthermore this is a core component of the library, used all over the codebase.

If it is not too late, I think a better naming convention should be used, something like `interaction_type`

**Comment by vmoens** [comment]
I agree with that, let's find a more suited name.
Also: what about using enum instead of strings for the interaction?
It would be faster to check `interaction_type is Interactions.MEAN` than `interaction_type == "mean"` + it would prevent people from mispselling or using names that don't exist.
Wdyt?

**Comment by matteobettini** [comment]
I am all in for the enum. I am an enum lover.

For the name anything works. 
`InteractionType` is the first that came to mind

**Comment by xuejun7777** [comment]
I hit following bug when I ran import torchrl
>>> import torchrl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "E:\rl\torchrl\__init__.py", line 32, in <module>
    import torchrl.collectors
  File "E:\rl\torchrl\collectors\__init__.py", line 6, in <module>
    from .collectors import (
  File "E:\rl\torchrl\collectors\collectors.py", line 40, in <module>
    from torchrl.envs.common import EnvBase
  File "E:\rl\torchrl\envs\__init__.py", line 6, in <module>
    from .common import EnvBase, EnvMetaData, make_tensordict
  File "E:\rl\torchrl\envs\common.py", line 27, in <module>
    from .utils import get_available_libraries, step_mdp
  File "E:\rl\torchrl\envs\utils.py", line 9, in <module>
    from tensordict.nn.probabilistic import (  # noqa
ImportError: cannot import name 'interaction_type' from 'tensordict.nn.probabilistic' (D:\anaconda\envs\rl\lib\site-packages\tensordict\nn\probabilistic.py)

And when I check "probabilistic.py",I found the "interaction_mode" in this script
<img width="287" alt="image" src="https://user-images.githubusercontent.com/100995171/232235597-133b83d1-9d81-47b6-a53e-215fa2a66ea8.png">

I think it may have something to do with what you were discussing,how can I fix it?

**Comment by vmoens** [comment]
What version of tensordict are you using?

**Comment by xuejun7777** [comment]
> What version of tensordict are you using?
pip show tensordict
Name: tensordict
Version: 0.1.0
Summary:
Home-page: https://github.com/pytorch-labs/tensordict
Author: tensordict contributors
Author-email: vmoens@fb.com
License: BSD
Location: d:\anaconda\envs\rl\lib\site-packages
Requires: cloudpickle, numpy, torch
Required-by: torchrl, torchrl-nightly

I installed as per the tutorial

**Comment by vmoens** [comment]
Try installing `pip install git+https://github.com/pytorch-labs/tensordict`, this should solve your issue.

**Comment by xuejun7777** [comment]
> Try installing `pip install git+https://github.com/pytorch-labs/tensordict`, this should solve your issue.

thanks!It works.
