### ISSUE TITLE
Documentation site down: 404 not found

### ISSUE THREAD

**Issue by amgawishx** [pytorch/rl#1031]
I have been trying access the `torchrl` documentation site provided at the following [link](https://pytorch.org/rl/) and I keep getting 404 page not found response like this:
![image](https://user-images.githubusercontent.com/26174499/230521714-da6f6b4b-cfe1-4d13-ac80-fea0088f3313.png)
Did it move to another site? I can't find any indications on that and this repo cites that link for the official documentation.

**Comment by HekpoMaH** [comment]
+1

Same here -- is anyone working on a fix?

**Comment by vmoens** [comment]
Not sure what broke there... I'll have a look asap

**Comment by vmoens** [comment]
The documentation is back online!
