### ISSUE TITLE
[BUG] ReplayBuffer improvements

### ISSUE THREAD

**Issue by yokaiAG** [pytorch/rl#1129]
Following our discussion on thread https://discuss.pytorch.org/t/rfc-torchrl-replay-buffers-pre-allocated-and-memory-mapped-experience-replay/155335/6

I present here the 3 issues (indexed A,B,C) encountered when using the TensorDictPrioritizedReplayBuffer.

My main issue was that the indices when calling memory.sample did not update and I was getting back always the same index 0 for all indices in the batch. This is corrected when I use the torchrl-nightly and the tensordict-nightly, as explained in the discussion thread above https://discuss.pytorch.org. Still some small issues remain. This is what i install and how i initialize memory

from torchrl.data import LazyTensorStorage, TensorDictPrioritizedReplayBuffer
from tensordict import TensorDict

memory = TensorDictPrioritizedReplayBuffer(alpha=0.7, beta=0.5, eps=0.01, storage=LazyTensorStorage(REPLAY_SIZE), batch_size=BATCH_SIZE)

Issue A) When i replace tensordict-nightly with tensordict I get an error, so there is incompatibility between torchrl-nightly and tensordict. (i need to use both nightly versions)

Issue B) In the torchrl versions (both released and nightly), when i use the private methods memory._sample and _get_priority: 

indx = memory.extend(data)
batch_sample, info = memory._sample(BATCH_SIZE)

print(“index”, batch_sample[“index”])
print(“priority”, [memory._get_priority(td) for td in batch_sample])

for td in batch_sample:
    print(‘samples’,td[‘action’])

i always get the same index 0 and the same priority using _get_priority

index tensor([0, 0, 0, 0, 0], dtype=torch.int32)
priority [1.4470902392888914, 1.4470902392888914, 1.4470902392888914, 1.4470902392888914, 1.4470902392888914]

However 5 samples for key-action in the batch are sampled correctly. )

samples tensor([8, 5, 6])
samples tensor([2, 2, 4])
samples tensor([8, 2, 7])
samples tensor([7, 1, 9])
samples tensor([7, 9, 7])

The problem with the index is corrected in the nightly version when i use memory.sample (non-private), but the _get_priority method still returns the vector of same values.

Issue C) For the sake of better clarity of the code and the variables, it would be great if the memory.sample(batch_size=BATCH_SIZE) command would return the sample dictionary containing also the priority values and not only the indices and 'weights'. Also, it would be nice to clarify what the difference is between ‘weights’ and ‘priorities’, as in the _get_priorities function, this is not clear.

**Comment by vmoens** [comment]
Thanks for posting this!
I created a tuto on replay buffer usage.
We'll work on addressing these before the next release.
