### ISSUE TITLE
[Feature Request] Objectives modules refactoring

### ISSUE THREAD

**Issue by Benjamin-eecs** [pytorch/rl#117]
## Motivation

I think we can refactor torchrl.objectives for functional programming.

## Solution

maybe change the inheritance of nn.modules, cc @waterhorse1  

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

**Comment by vmoens** [comment]
@Benjamin-eecs it was closed automatically because of the linked issues 😅

**Comment by Benjamin-eecs** [comment]
Yeah, it happens when trying to track multiple related PR, it's alright. May have to manually reopen every time :)
