### ISSUE TITLE
Install torchrl failed, PyCharm

### ISSUE THREAD

**Issue by Killpit** [pytorch/rl#1176]
ERROR: Could not find a version that satisfies the requirement torchrl (from versions: none)
ERROR: No matching distribution found for torchrl

(venv) atatekeli:PyTorchProjects atatekeli$ pip install torchrl
ERROR: Could not find a version that satisfies the requirement torchrl (from versions: none)
ERROR: No matching distribution found for torchrl
## Screen
<img width="1440" alt="Ekran Resmi 2023-05-22 14 42 37" src="https://github.com/pytorch/rl/assets/57031187/3456cd13-82c3-4074-abc7-91624bdaf1da">
shots

## System info
<img width="1440" alt="Ekran Resmi 2023-05-22 14 42 37" src="https://github.com/pytorch/rl/assets/57031187/86c5f396-a86f-4a0e-9a16-07c590989f38">

Describe the characteristic of your environment:
 * I was trying to install torchrl by using PyCharm's venv
 * 3.10.10
 * torch: 2.0.1, torchvision: 0.15.2

**Comment by vmoens** [comment]
Thanks for reporting this
Seems like you're on OsX. Is it an apple silicon CPU?
If so you may just need to do
```
pip install git+https://github.com/pytorch/rl@0.1.1
```
Let us know if that works!

**Comment by Killpit** [comment]
No it didn't 

(venv) atatekeli:PyTorchProjects atatekeli$ pip install git+https://github.com/pytorch/rl@0.1.1
Collecting git+https://github.com/pytorch/rl@0.1.1
  Cloning https://github.com/pytorch/rl (to revision 0.1.1) to /private/var/folders/y4/jnpd1pl92r50hk6sfmrcq20c0000gn/T/pip-req-build-qx40xmf6
  Running command git clone --filter=blob:none --quiet https://github.com/pytorch/rl /private/var/folders/y4/jnpd1pl92r50hk6sfmrcq20c0000gn/T/pip-req-build-qx40xmf6
  WARNING: Did not find branch or tag '0.1.1', assuming revision or ref.
  Running command git checkout -q 0.1.1
  error: pathspec '0.1.1' did not match any file(s) known to git
  error: subprocess-exited-with-error
  
  × git checkout -q 0.1.1 did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git checkout -q 0.1.1 did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by vmoens** [comment]
My bad this should work
```
pip install git+https://github.com/pytorch/rl@v0.1.1
```

**Comment by Killpit** [comment]
This is what it looks like

Successfully built torchrl
Installing collected packages: cloudpickle, tensordict, torchrl
Successfully installed cloudpickle-2.2.1 tensordict-0.1.2 torchrl-0.1.1+6d030c9

**Comment by Killpit** [comment]
Time to create RL models I suppose
