### ISSUE TITLE
[Feature Request] CatTensors could delete now empty nested tensordicts

### ISSUE THREAD

**Issue by duburcqa** [pytorch/rl#1200]
## Motivation

The current implementation of `CatTensor` can process nested keys and delete them afterward. It is great and works just fine. However, It may be convenient to better handle keys mapping to `TensorDict` objects. Currently, only leaves can be provided. So, I'm just gathering all of them in a list. If I do so, it does what it is supposed to do, but do not delete the highest-level key which is now mapping to an empty `TensorDict`.

## Solution

One option would be to support providing keys mapping to `TensorDict` objects out-of-the-box, so that it knows it should process of the leaves internally and delete the top-level key. 

## Alternatives

Another option would just be to check for all any empty `tensorDict` after processing of all leave-keys and delete them (maybe only checking the common roots of the provided keys). In the later case, it would be great to add an assert to check that the provided keys are truly associated to leaves.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

**Comment by vmoens** [comment]
In your case, maybe we could directly provide the parent tensordict as a key, rather than giving all its leaves?
That way we don't have to make the (opinionated) choice to remove an empty tensordict?

**Comment by duburcqa** [comment]
Yes it is exactly this, I should I provided a snipped example, sorry about that ! 

Because in this case, I tried to pass `t = CatTensors(in_keys=["root"])` directly and it does not work but I will check again on my actual setup because it seems to work on your snippet.

**Comment by duburcqa** [comment]
I also tried to cleanup using `ExcludeTransform` but it caused some other issue when collecting rollouts.

**Comment by duburcqa** [comment]
Actually I found out why it does not work on an actual env to pass the top-level keys to concatenate directly. It is because the field `batch_size` is empty sicne there is none at this point. I don't know if it is a bug or expected. Here is the trace I'm getting:
```python
    eval_env = TransformedEnv(
        eval_env, 
        CatTensors(
            in_keys=list(eval_env.observation_spec.keys(
                include_nested=True, leaves_only=True)),
            out_key="observation_flat",
            del_keys=True,
            dim=-1,
        )
    )
    
IndexError: tuple index out of range
> /home/duburcqa/.local/lib/python3.10/site-packages/tensordict/tensordict.py(4373)<listcomp>()
   4371             f"={dim} and batch_size={batch_size}"
   4372         )
-> 4373     batch_size[dim] = sum([td.batch_size[dim] for td in list_of_tensordicts])
   4374     batch_size = torch.Size(batch_size)
   4375 

ipdb> td
TensorDict(
    fields={
        Q: Tensor(shape=torch.Size([19]), device=cuda:0, dtype=torch.float64, is_shared=True),
        V: Tensor(shape=torch.Size([18]), device=cuda:0, dtype=torch.float64, is_shared=True)},
    batch_size=torch.Size([]),
    device=cuda:0,
    is_shared=True) 
```
