### ISSUE TITLE
[BUG] Buggy `fake_tensordict()`

### ISSUE THREAD

**Issue by matteobettini** [pytorch/rl#1260]
In `fake_tensordict()` the following lines are executed
```
  next_output = fake_obs.clone()
  next_output.update(fake_reward)
  next_output.update(fake_done)
```
they will crash as soon as the shape of the observation spec differs from the shape of done or reward.

For example in my case it crashes with
```
fake_obs.batch_size = [600,3]
fake_done.batch_size = [600,1]
```
given that the obs are multiagent and the done is shared

**Comment by matteobettini** [comment]
May be fixed by adding
`next_output.batch_size = self.batch_size`
at 
https://github.com/pytorch/rl/blob/main/torchrl/envs/common.py#L1326

**Comment by vmoens** [comment]
What do these specs look like? Shouldn't all the roots be enforced to have the same batch size as the env, and only allow lower levels to have more tailored shapes?

**Comment by vmoens** [comment]
> `next_output.batch_size = self.batch_size`

The problem with this solution is that resetting the batch size of the root tensordict overrides the one of the leafs too.
It's a hard design choice: if we don't do it, it may be surprising that overriding the root does not modify anythink downstream

**Comment by matteobettini** [comment]
> > `next_output.batch_size = self.batch_size`
> 
> The problem with this solution is that resetting the batch size of the root tensordict overrides the one of the leafs too. It's a hard design choice: if we don't do it, it may be surprising that overriding the root does not modify anythink downstream

Is this the case for specs of for tensordicts?
For tensordicts it does not seem to be the case (I use this a lot in my code).

For example that linecurrently runs as
```
next_output = TensorDict(
    fields={
        agents: TensorDict(
            fields={
                info: TensorDict(
                    fields={
                        ground_rew: Tensor(shape=torch.Size([600, 3, 1]), device=cpu, dtype=torch.float32, is_shared=False),
                        pos_rew: Tensor(shape=torch.Size([600, 3, 1]), device=cpu, dtype=torch.float32, is_shared=False)},
                    batch_size=torch.Size([600, 3]),
                    device=cpu,
                    is_shared=False),
                observation: Tensor(shape=torch.Size([600, 3, 16]), device=cpu, dtype=torch.float32, is_shared=False)},
            batch_size=torch.Size([600, 3]),
            device=cpu,
            is_shared=False)},
    batch_size=torch.Size([600, 3]),
    device=cpu,
    is_shared=False)
```

```
next_output.batch_size = self.batch_size
```

```
next_output = TensorDict(
    fields={
        agents: TensorDict(
            fields={
                info: TensorDict(
                    fields={
                        ground_rew: Tensor(shape=torch.Size([600, 3, 1]), device=cpu, dtype=torch.float32, is_shared=False),
                        pos_rew: Tensor(shape=torch.Size([600, 3, 1]), device=cpu, dtype=torch.float32, is_shared=False)},
                    batch_size=torch.Size([600, 3]),
                    device=cpu,
                    is_shared=False),
                observation: Tensor(shape=torch.Size([600, 3, 16]), device=cpu, dtype=torch.float32, is_shared=False)},
            batch_size=torch.Size([600, 3]),
            device=cpu,
            is_shared=False)},
    batch_size=torch.Size([600]),
    device=cpu,
    is_shared=False)

```

**Comment by matteobettini** [comment]
> What do these specs look like? Shouldn't all the roots be enforced to have the same batch size as the env, and only allow lower levels to have more tailored shapes?

Ok I imporved my specs to match this constraint you mentioned and it works.
But if this is a contraint we might need to be clearer about it

**Comment by vmoens** [comment]
Yep we could check that the root composite always has the right shape and otherwise give an informed error message!

**Comment by matteobettini** [comment]
Yep

> The problem with this solution is that resetting the batch size of the root tensordict overrides the one of the leafs too.
> It's a hard design choice: if we don't do it, it may be surprising that overriding the root does not modify anythink downstream

Just to reiterate on this, I think this is not currently the case and we should not enforce this

**Comment by vmoens** [comment]
Oh yeah my mistake, here's what currently happens: the batch size of the leafs is overridden iif it would not be possible to have the same batch size as before after resetting it.

```python
>>> from tensordict import TensorDict
>>> td = TensorDict({"a": {"b": [1, 2, 3]}}, [])
>>> td.batch_size = [3]
>>> td["a"] # batch size has changed
TensorDict(
    fields={
        b: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.int64, is_shared=False)},
    batch_size=torch.Size([3]),
    device=None,
    is_shared=False)
>>> td.batch_size = []
>>> td["a"] # batch size has not changed
TensorDict(
    fields={
        b: Tensor(shape=torch.Size([3]), device=cpu, dtype=torch.int64, is_shared=False)},
    batch_size=torch.Size([3]),
    device=None,
    is_shared=False)


```
