### ISSUE TITLE
[BUG] GymWrapper: AttributeError: module 'gym' has no attribute '__version__'

### ISSUE THREAD

**Issue by axelbr** [pytorch/rl#1275]
## Describe the bug

When using `GymWrapper`, I get the following error:
`AttributeError: module 'gym' has no attribute '__version__`

## To Reproduce

```python
import gymnasium
from torchrl.envs.libs.gym import GymWrapper

if __name__ == '__main__':
    env = gymnasium.make(id="CartPole-v1")
    env = GymWrapper(env)
```

```bash
Traceback (most recent call last):
  File "project/training/trl.py", line 3, in <module>
    from torchrl.envs.libs.gym import GymWrapper
  File "project/venv/lib/python3.8/site-packages/torchrl/envs/libs/gym.py", line 276, in <module>
    def _get_gym_envs():  # noqa: F811
  File "project/venv/lib/python3.8/site-packages/torchrl/_utils.py", line 325, in __call__
    version = self.import_module(self.module_name)
  File "project/venv/lib/python3.8/site-packages/torchrl/_utils.py", line 289, in import_module
    return module.__version__
AttributeError: module 'gym' has no attribute '__version__'
```

## Expected behavior

A TorchRL environment should be created.

## System info

Describe the characteristic of your environment:
- pip
- 3.8
- gymnasium==0.28.1

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
I can't reproduce this on main, can you try to `pip install git+https://github.com/pytorch/rl`?

**Comment by axelbr** [comment]
Ok, I was using the latest version from pypi. When installing directly from main, I get another error:
`ImportError: cannot import name 'unravel_keys' from 'tensordict.utils' (project/venv/lib/python3.8/site-packages/tensordict/utils.py)`

But I get this error whenever I try to import torchrl.

**Comment by vmoens** [comment]
You should upgrade tensordict to the nightlies too!
