### ISSUE TITLE
[BUG] Import error 

### ISSUE THREAD

**Issue by davidireland3** [pytorch/rl#1308]
There seems to be an import error when, after `pip` installing `torchrl`, in python it cannot find some packages that it needs. 

the error message when trying `import torchrl` in python:

```
ImportError: dlopen(/Users/davidireland/opt/anaconda3/envs/hrl2/lib/python3.9/site-packages/torchrl/_torchrl.so, 0x0002): Symbol not found: __ZN8pybind116detail11type_casterIN2at6TensorEvE4castERKS3_NS_19return_value_policyENS_6handleE
  Referenced from: <26B157A6-9DAD-3C58-9A74-E4A5EEF6F011> /Users/davidireland/opt/anaconda3/envs/hrl2/lib/python3.9/site-packages/torchrl/_torchrl.so
  Expected in:     <8F09D9D9-3AB7-367A-B2FF-80087FA15C9E> /Users/davidireland/opt/anaconda3/envs/hrl2/lib/python3.9/site-packages/torch/lib/libtorch_python.dylib
```

**Comment by vmoens** [comment]
What version of pytorch are you using? It seems it is not synced with torch.
It should work with torch 2.0.1
If you are using the nightlies it's 2.1.0dev

**Comment by davidireland3** [comment]
thanks, I was on 1.x.x. I've updated to 2.0.1 and `torchrl` imports fine now!
