### ISSUE TITLE
[BUG] Misleading docs - NoisyLinear

### ISSUE THREAD

**Issue by maayanorner** [pytorch/rl#1320]
NoisyLinear is documented to have std_init of 1, but it really has a std_init of 0.1.
You can see it in the code or even in the docstring-generated function signature here:
https://pytorch.org/rl/reference/generated/torchrl.modules.NoisyLinear.html

Clearly, it's very misleading.
Thanks!

**Comment by vmoens** [comment]
Thanks for reporting this!
Should be fixed now
