### ISSUE TITLE
[Feature Request] Trainer saving and loading utils

### ISSUE THREAD

**Issue by vmoens** [pytorch/rl#14]
The `Trainer` class supports saving model and environment variables in order for them to be re-used. However this workflow is still experimental. 
Eventually, it should be possible to save and load an agent state and restart training where it was left.

**Comment by Benjamin-eecs** [comment]
Now that `agent` class is gone, I think it is safe to close this issue.

**Comment by vmoens** [comment]
You're right. We should edit it with Trainer instead

**Comment by Benjamin-eecs** [comment]
I think it can be considered done in `trainer` class.
