### ISSUE TITLE
[Question] Video recording for the PPO example

### ISSUE THREAD

**Issue by ADebor** [pytorch/rl#1400]
Hi there,

I've just started following the tutorials, and at the end of the "RL (PPO) with TorchRL" tuto, you mention that one could add a `VideoRecorder` transform to the environment to log the visual rendering of the environment. I thus tried to add such a transform to the environment (in the `Compose` of the `TransformedEnv`) by first creating a Logger instance (with logger type wandb), and I tried different combinations of args for the environment: adding `render_mode`, `from_pixels`, and `pixel_only` args. 

Unfortunately, I'm not able to record a video. My runs appear in my wandb workspace, but no video. I'm probably missing something here (sorry for the silly question), but I'd be happy if you could provide me with the small bits of code I need to add in the example to record the pendulum in action.

Thank you in advance for the help, and thank you for the library!

**Comment by vmoens** [comment]
Thanks for reporting! I'll investigate this asap!

**Comment by Alpergece** [comment]
I faced with the exact same problem. Do you have an update regarding VideoRecorder?

**Comment by ADebor** [comment]
That's what I was expecting indeed, and it works with the PPO example as well, thank you! Will close the issue if @Alpergece's problem is solved.

**Comment by glucoseJelly** [comment]
Hello, I also work on with the PPO tutorials and I'm struggling about saving video as local mp4 file.

Here is my current code, and I changed points are just adding `VideoRecorder` with `CSVLogger` in `Compose`. 
https://gist.github.com/glucoseJelly/985b1b06af0ab1f8136c1e1b1af3ff89

And this code cause below error:
```
 File "/home/username/.local/lib/python3.10/site-packages/torchrl/record/recorder.py", line 75, in _apply_transform
    raise RuntimeError(f"Invalid observation shape, got: {observation.shape}")
RuntimeError: Invalid observation shape, got: torch.Size([11])
```
I'm using torchrl's version is 0.1.1.

I would appreciate it if anyone help. Thank you.

**Comment by vmoens** [comment]
You need to put `from_pixels=True, pixels_only=False` in the base env that you are using for testing, as well as renaming the key to pixels in the video recorder

**Comment by lucasbasquerotto** [comment]
Thanks! I tried to find documentation about the use of VideoRecorder but it has very little explanation on how to use it, just a very vague reference.

To make it work, I changed the environment creation to do the video recording as:

```py
# from torchrl.envs import ParallelEnv
from torchrl.record import VideoRecorder
from torchrl.record.loggers.wandb import WandbLogger

def make_env():
    logger = WandbLogger(exp_name="ppo", project="test")

    inner_env = TransformedEnv(
        GymEnv(
            "InvertedDoublePendulum-v4", 
            from_pixels=True,
            pixels_only=False,
            device=device, 
            frame_skip=frame_skip, 
            # render_mode="human"
        ),
        Compose(
            VideoRecorder(logger=logger, tag="ppo video"),
            # normalize observations
            ObservationNorm(in_keys=["observation"]),
            DoubleToFloat(in_keys=["observation"]),
            StepCounter(),
        ),
    )

    inner_env.transform[1].init_stats(num_iter=1000, reduce_dim=0, cat_dim=0)

    return inner_env

env = make_env()

check_env_specs(env)

# env = ParallelEnv(3, make_env)

print("env:", env)
```

The `from_pixels=True` is needed to generate the video (the `VideoRecorder` transform expects `pixels` as a key) and the `pixels_only=False` is needed because the `observation` key ir required too (the other transforms use it).

Then I just need to dump it after each rollout:

```py
eval_rollout = env.rollout(1000, policy_module)
env.transform[0].dump()
```

**Comment by vmoens** [comment]
I'll clarify the doc tomorrow thanks for pointing it out!

**Comment by lucasbasquerotto** [comment]
@vmoens Thanks 👍
