### ISSUE TITLE
 [BUG]  The actor_params attribute is lost when passing a Loss module to a multiprocessing process

### ISSUE THREAD

**Issue by albertbou92** [pytorch/rl#1407]
## Describe the bug

When passing a Loss module to another mp process, the actor_params attribute seems to be lost.

The problem is not present when deepcopying the module or when pickling and unpickling it.

## To Reproduce

Steps to reproduce the behavior.

```python
import sys
import pickle
from copy import deepcopy
from torch import nn
from torch import multiprocessing as mp
from tensordict.nn import TensorDictModule
from torchrl.objectives import PPOLoss
from torchrl.envs.libs.gym import GymEnv
from torchrl.collectors import SyncDataCollector
from torchrl.objectives.value.advantages import GAE
from torchrl.modules import OneHotCategorical, ProbabilisticActor


def run_collector(mp_collector, mp_advantage, mp_loss,  qout):
    for batch in mp_collector:
        try:
            batch = mp_advantage(batch)
            loss = mp_loss(batch)
            qout.put("succeeded")
            print('succeeded')
        except AttributeError:  #  AttributeError: 'PPOLoss' object has no attribute 'actor_params'
            qout.put("failed")
            print('failed')


if __name__ == "__main__":

    def env_maker():
        return GymEnv("CartPole-v1", device="cpu")

    test_env = env_maker()
    action_spec = test_env.action_spec
    obs_spec = test_env.observation_spec
    n = action_spec.space.n
    actor = ProbabilisticActor(
        module=TensorDictModule(nn.Linear(4, n), in_keys=["observation"], out_keys=["logits"]),
        in_keys=["logits"],
        out_keys=["action"],
        distribution_class=OneHotCategorical,
        return_log_prob=True,
        spec=action_spec)
    critic = TensorDictModule(nn.Linear(4, 1), in_keys=["observation"], out_keys=["state_value"])

    collector = SyncDataCollector(
        env_maker,
        actor,
        total_frames=200,
        frames_per_batch=200,
    )

    advantage_module = GAE(
        gamma=0.99,
        lmbda=0.95,
        value_network=critic,
        average_gae=True,
        advantage_key="advantage",
    )
    loss_module = PPOLoss(actor=actor, critic=critic)

    # The attribute actor_params is present here
    assert hasattr(loss_module, "actor_params")

    # 1. The attribute is still present after deepcopying the loss_module
    deepcopy_loss_module = deepcopy(loss_module)
    assert hasattr(deepcopy_loss_module, "actor_params")

    # 2. The attribute is still present after pickling and unpickling the loss_module
    # Pickle the object
    serialized = pickle.dumps(loss_module)
    # Unpickle the object
    loss_module2 = pickle.loads(serialized)
    assert hasattr(loss_module2, "actor_params")

    # 3. The problem is appears when copying the loss_module to the child process
    qout = mp.Queue(1)
    p = mp.Process(target=run_collector, args=(collector, advantage_module, loss_module, qout))
    p.start()
    assert qout.get() == "succeeded"
    p.join()
```

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Thanks for pointing this.
The issue is a bit weird but let me explain:
We register the params under `_actor_params` and during construciton we augment the loss class with a `actor_param` property.
This is far from optimal since it means that all the instances of that class will have an `actor_params` property even if they don't have `_actor_params`. Plus, when we send the object to another process, the instance will not have gone through `__init__` so it won't have the property set.
We should change that logic. In general, I've never been fond of this implementation where the actor params in accessed via a property, it should be accessed directly. I will attempt to see what I can do to fix that during the week.

**Comment by albertbou92** [comment]
The previous error (AttributeError: 'PPOLoss' object has no attribute 'actor_params') seems indeed gone thanks! However, when I run the reproducer code a new error appears.

> TypeError: _generator_ctor() takes from 0 to 1 positional arguments but 2 were given

can you reproduce it? I can provide the whole traceback otherwise

**Comment by vmoens** [comment]
I still need to fix this haha! No idea why the previous error has disappeared! Should be done by EOD
