### ISSUE TITLE
[BUG] Replay buffer is not picklable

### ISSUE THREAD

**Issue by albertbou92** [pytorch/rl#1408]
## Describe the bug

The ReplayBuffer class is not pickable because it contains '_thread.RLock' objects. 

@vmoens I would like to give this one a shot. could you point me in the right direction? does the __reduce__() method need to be adapted? 

## To Reproduce

Steps to reproduce the behavior.

```python
import pickle
from torchrl.data import LazyMemmapStorage, TensorDictReplayBuffer
from torchrl.data.replay_buffers.samplers import SamplerWithoutReplacement


if __name__ == "__main__":

    sampler = SamplerWithoutReplacement()
    buffer = TensorDictReplayBuffer(
        storage=LazyMemmapStorage(200),
        sampler=sampler,
        batch_size=200,
    )

    serialized = pickle.dumps(buffer)  # *** TypeError: cannot pickle '_thread.RLock' object
```

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
To solve this:
Look at this [legacy code of tensordict](https://github.com/pytorch-labs/tensordict/blob/38f89ed91a888ea2e1020b00d8f334a68a0a3eee/tensordict/tensordict.py#L361-L366). 
The `__getstate__` returns a dictionary like `self.__dict__`. What we need to do is to pop the value of the lock, replace it with something (e.g. a string) that will tell `__setstate__` what to do.
Then in `__setstate__`, you pop that placeholder and do what you want.
Here's a high level example:

```python
    def __getstate__(self) -> dict[str, Any]:
        state = self.__dict__.copy()
        _replay_lock = state.pop('_replay_lock', None)
        _futures_lock = state.pop('_futures_lock', None)
        if _replay_lock is not None:
            state['_replay_lock_placeholder'] = None
        # same with future
        return state

    def __setstate__(self, state: dict[str, Any]) -> dict[str, Any]:
        _replay_lock_placeholder = state.pop('_replay_lock_placeholder', None)
        if _replay_lock_placeholder is not None:
            _replay_lock = threading.RLock()
            state['_replay_lock'] = _replay_lock
        # same with future
        self.__dict__.update(state)
```

**Comment by albertbou92** [comment]
It was solved in https://github.com/pytorch/rl/pull/1410, so I am closing the issue
