### ISSUE TITLE
 [Feature Request] Add support to python 3.11 at the nightly verision

### ISSUE THREAD

**Issue by chriss1245** [pytorch/rl#1469]
## Solution
Add in PyPI package for python 3.11

## Alternatives
I  was wondering when you were going to release support for python 3.11 at least in the nightly version. 

## Additional context
I don't know how hard is it to be fair. But I think there was already a pull request which solved that and has been already merged.  
See #1433

**Comment by vmoens** [comment]
[Completed](https://pypi.org/project/torchrl-nightly/#history)
