### ISSUE TITLE
[BUG] Unsqueezing the error in ddpg

### ISSUE THREAD

**Issue by matteobettini** [pytorch/rl#1486]
https://github.com/pytorch/rl/blob/3595c45eeb0c3e45c41bfff99ecbc973a7d1704f/torchrl/objectives/ddpg.py#L272

this line is not compatible with multi-agent, as it unsuquezees a dimension before the agents one.

Is there a workaround? is a `unsqueeze(-1)` sufficient?

**Comment by vmoens** [comment]
Yeah should work!

**Comment by matteobettini** [comment]
Or maybe we can just remove it? What is the reason for that line?
