### ISSUE TITLE
[Feature Request] Algorithm: Implement Decision Transformer

### ISSUE THREAD

**Issue by vmoens** [pytorch/rl#15]
Implement Decision Transformer as presented in https://arxiv.org/abs/2106.01345

**Comment by badhorse666** [comment]
Hi, I'd like to contribute to this project and came across this issue. Wondering what the status of this issue is. I'd like to work on it if it's still open and needs work.

**Comment by vmoens** [comment]
Thanks for the interest @badhorse666 ! 
We've [closed this](#1149) (sorry I forgot to actually close it) but we're looking for people to help us fix our implementation of Dreamer, would you be interested in helping with that?

**Comment by badhorse666** [comment]
Hi @vmoens , thanks for the reply! Yes totally. If you would be so kind to provide some pointers, I'd love to start looking into it.
