### ISSUE TITLE
[BUG] Cannot import torchrl on M2 MacBook Pro when install from Git repo.

### ISSUE THREAD

**Issue by EkaterinaAbramova** [pytorch/rl#1582]
## Describe the bug

Cannot import torchrl on M2 MacBook Pro when install from Git repo.

## To Reproduce

I have installed torchrl from GitHub following the online instructions from your repo:
```
git clone https://github.com/pytorch/rl
cd /path/to/torchrl/
pip install -e .
```
Issue 1 [suggested resolution]: the path setup worked for rl/ folder not torchrl/ as the setup.py is inside rl not torchrl. So that instruction should updated in your docs please.
Issue 2 [unresolved]: it says this should work straight out of the box on M1. I have the M2 and when I `import torch` it is ok, but when I `import torchrl` I get the following error: `ImportError: cannot import name 'unravel_key' from 'tensordict' (/Users/myname/anaconda3/envs/gpu-torch-rl/lib/python3.10/site-packages/tensordict/__init__.py) `

## Expected behavior

I expect to be able to import the torchrl library. 

## Screenshots

<img width="746" alt="Screenshot 2023-09-29 at 12 14 33" src="https://github.com/pytorch/rl/assets/1406362/9cdc670e-0aa8-4185-a281-b6d54ca4fd8f">

## System info

Apple M2 max
Version 13.5.2

Describe the characteristic of your environment:

Steps Ive taken up until the error:

```python
conda create --name gpu-torch-rl python=3.10 spyder=5.4.3
conda activate gpu-torch-rl

git clone https://github.com/pytorch/rl /Users/myname/anaconda3/repos/rl

cd /Users/myname/anaconda3/repos/rl/
pip install -e .
```

## Additional context

I also tried to get the tensordict from GitHub to resolve this unravel key issue, and tried:
```
pip uninstall tensordict
pip install git+https://github.com/pytorch-labs/tensordict
```
which resolved this issue, however I had a bunch of other issues after that, so am keen to understand why the tensordict that came together with the torchrl download didn't work. Surely it should be compatible. Could you please resolve this issue?

**Comment by vmoens** [comment]
Hello!
TorchRL's development is currently tightly linked to tensordict hence if you install the nightlies of one you should also do the same with the other. In the future, we'll make sure that things are properly linked so that a proper error (or even better, the accurate nightlies) are installed with the lib!

Regarding M2 compatibility, we're still looging at making those wheels. I hope to have an answer to share early next week!

**Comment by EkaterinaAbramova** [comment]
Thank you for your reply! Could you please kindly recommend how I can use the apple metal MPS with the tutorial https://pytorch.org/tutorials/intermediate/reinforcement_ppo.html ? I am trying to get rid of the **TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.** . Is there something I can change globally to avoid this issue? Where shall I change the type from float64 to float32 (such that it works globally without me having to go into every single file and say if mps and float64 then change to float32?

**Comment by vmoens** [comment]
See https://github.com/pytorch/rl/pull/1472#issuecomment-1741953667
