### ISSUE TITLE
[BUG] cannot use GymEnv() says '_set_gym_args' has not been found

### ISSUE THREAD

**Issue by EkaterinaAbramova** [pytorch/rl#1583]
## Describe the bug

The following is not working:
```
base_env = GymEnv("InvertedDoublePendulum-v4", device=device, frame_skip=frame_skip)
ModuleNotFoundError: Supported version of '_set_gym_args' has not been found.
```

## To Reproduce

```python
conda create --name gpu-torch-rl python=3.10 spyder=5.4.3
conda activate gpu-torch-rl

git clone https://github.com/pytorch/rl /Users/bondgirl007/anaconda3/repos/rl

cd /Users/bondgirl007/anaconda3/repos/rl/
pip install -e .

pip uninstall tensordict
pip install git+https://github.com/pytorch-labs/tensordict
```

Then I am trying to run this tutorial from PyTorch: https://pytorch.org/tutorials/intermediate/reinforcement_ppo.html
Everything up until this line is ok, but then the line doesn't run:
`base_env = GymEnv("InvertedDoublePendulum-v4", device=device, frame_skip=frame_skip)`

## Expected behavior

to obtain base_env after calling GymEnv()

## Screenshots

<img width="748" alt="Screenshot 2023-09-29 at 12 33 14" src="https://github.com/pytorch/rl/assets/1406362/cb705701-a03a-4af1-b899-db7c22fec1c6">

## System info

MacBook Pro M2 max
Version: 13.5.2

```python
import torchrl, numpy, sys
print(torchrl.__version__, numpy.__version__, sys.version, sys.platform)
0.1.1+18b33fe 1.26.0 3.10.13 (main, Sep 11 2023, 08:16:02) [Clang 14.0.6 ] darwin
```

**Comment by EkaterinaAbramova** [comment]
These seemed to have resolved the issue: 
Supported version of '_set_gym_args' has not been found.
pip install gym --upgrade

DependencyNotInstalled: No module named 'mujoco'.
pip install mujoco

Sounds like something needs to be updated in the git download of torchrl, so that all of above doesn't happen for others.

**Comment by vmoens** [comment]
I believe this is due to a gym/gymnasium mismatch. 
You can usually solve these issues with
```python
with set_gym_backend("gym"):
    env = GymEnv(...)
```
that redirects all the decorated code to use gym (or gymnasium).
We had a thorough refactoring of our gym interactions in #1539 so now things should work more smoothly

**Comment by skandermoalla** [comment]
@vmoens I think @EkaterinaAbramova here just installed `torchrl` without any of the RL packages (`gym`, `mujoco`, etc.), and although this is a feature of TorchRL to not come with any of these dependencies, the first error message that a user encounters when creating a gym env is
`ModuleNotFoundError: Supported version of 'torchrl.envs.libs.gym.GymEnv._set_gym_args' has not been found.`
Which somehow hides the fact that the user is missing gym in their environment. Maybe this is an opportunity to catch that in `_set_gym_args` and improve its error message?

**Comment by vmoens** [comment]
Oh good catch thanks!
Indeed, we assume that people have installed everything in some weird places, it's true that the entry point of the gym classes isn't as obvious as I thought.
