### ISSUE TITLE
[Feature Request] Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.

### ISSUE THREAD

**Issue by EkaterinaAbramova** [pytorch/rl#1584]
## Motivation

I am following this tutorial using M2 Max MacBook Pro and am getting an issue with running:
`base_env = GymEnv("InvertedDoublePendulum-v4", device=device, frame_skip=frame_skip)`
The error is: 
```
File ~/anaconda3/repos/rl/torchrl/envs/libs/gym.py:274 in _gym_to_torchrl_spec_transform
    low = torch.tensor(spec.low, device=device, dtype=dtype)

TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.
```

I understand this is to do with the MacBook Metal, however is it possible to have edits to the torchrl code such that it would run on the Mac gpus? It would be most helpful to understand how I can resolve this issue on my end. Is there anything I can set globally?

<img width="747" alt="Screenshot 2023-09-29 at 12 59 11" src="https://github.com/pytorch/rl/assets/1406362/cacd6a96-8e0e-46d5-a3b3-8e52397da4b9">

**Comment by vmoens** [comment]
See https://github.com/pytorch/rl/pull/1472#issuecomment-1741953667 for follow-up, closing as duplicate
