### ISSUE TITLE
[BUG] `SACLoss` cannot be loaded from `state_dict`

### ISSUE THREAD

**Issue by matteobettini** [pytorch/rl#1594]
The SACLoss has a `target_entropy_buffer` which is instantiated not at init time but lazily https://github.com/pytorch/rl/blob/106368ffe627aada70ebb33ecf545d0f193c7757/torchrl/objectives/sac.py#L424

This is a problem as it will prevent reloading this loss from `state_dict`.

What will happen is that `state_dict` will likely contain this buffer and the reloaded loss will not (as the lazy step has not happened yet)

## Solution
We instantiate all buffers at init time. That seems the only way to me to support loading from `state_dict`

**Comment by vmoens** [comment]
"the only way" is rarely true :) 
Can you describe the problem more in details, ie what you're trying to do (when do you save / when do you load etc)?

**Comment by matteobettini** [comment]
Sorry, here is the example
```python
import torch

from torchrl.data import UnboundedContinuousTensorSpec
from torchrl.modules import QValueActor, ProbabilisticActor, TanhDelta, ValueOperator
from tensordict.nn import TensorDictModule

from torchrl.objectives import SACLoss

if __name__ == "__main__":
    model = torch.nn.Linear(3, 4)  # does not work
    # model = torch.nn.Linear(1, 1) works
    actor_module = TensorDictModule(
        torch.nn.Linear(3, 4), in_keys=["obs"], out_keys=["logits"]
    )
    policy = ProbabilisticActor(
        module=actor_module,
        in_keys=["logits"],
        out_keys=["action"],
        distribution_class=TanhDelta,
    )
    value = ValueOperator(module=model, in_keys=["obs"], out_keys="value")

    loss = SACLoss(
        actor_network=policy,
        qvalue_network=value,
        action_spec=UnboundedContinuousTensorSpec(shape=(2,)),
    )
    _ = (
        loss.target_entropy
    )  # This instantiates a buffer. It is called during the forward pass. Here we call it to emulate a forward
    state = loss.state_dict()

    loss = SACLoss(
        actor_network=policy,
        qvalue_network=value,
        action_spec=UnboundedContinuousTensorSpec(shape=(2,)),
    )
    loss.load_state_dict(
        state
    )  # The loss.target_entropy was in the state_dict but cannot be found in the loss as it does not exist yet

```

```bash
Traceback (most recent call last):
  File "/Users/matbet/PycharmProjects/rl/prova.py", line 30, in <module>
    loss.load_state_dict(
  File "/Users/matbet/miniconda3/envs/torchrl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SACLoss:
	Unexpected key(s) in state_dict: "target_entropy_buffer". 
```

**Comment by matteobettini** [comment]
one simple solution is calling `_ = self.target_entropy` in the init of the loss. Or transfer the whole logic of `self.target_entropy` in init like it is done in `DiscreteSACLoss`

**Comment by vmoens** [comment]
Let me refactor that

**Comment by vmoens** [comment]
We need this to be instantiated before the keys are set, because it reads the action key in the action spec. So that can't be done in `__init__`.
I wonder why we can make it in the discrete case though...
My suggestion is to make it happen in state_dict if it's not done already

**Comment by matteobettini** [comment]
sorry you can ignore that part

**Comment by matteobettini** [comment]
in the discrete case it takes as input an argument `n_actions` and uses that to compute the target entropy so it does not need keys
