### ISSUE TITLE
[BUG]ModuleNotFoundError: No module named 'torchrl._torchrl'

### ISSUE THREAD

**Issue by jiagpaopao** [pytorch/rl#1595]
## To Reproduce

Steps to reproduce the behavior.

Please try to provide a minimal example to reproduce the bug. Error messages and stack traces are also helpful.

Please use the markdown code blocks for both code and stack traces.

```python
import torchrl
```

```bash
Traceback (most recent call last):
  File ... 
```

## System info

Describe the characteristic of your environment:
 * Describe how the library was installed (pip, source, ...)
 * Python version
 * Versions of any other relevant libraries

```python
import torchrl, numpy, sys
print(torchrl.__version__, numpy.__version__, sys.version, sys.platform)
```

## Reason and Possible fixes

If you know or suspect the reason for this bug, paste the code lines and suggest modifications.

## Checklist

- [ ] I have checked that there is no similar issue in the repo (**required**)
- [ ] I have read the [documentation](https://githubfast.com/pytorch/rl/tree/main/docs/) (**required**)
- [ ] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Thanks for this @jiagpaopao 
Can you provide more context? How you installed the lib, what machine you're using, what you have tried to debug it (if anything).
Thanks

**Comment by jiagpaopao** [comment]
> Thanks for this @jiagpaopao感谢您的@jiagpaopao Can you provide more context? How you installed the lib, what machine you're using, what you have tried to debug it (if anything).你能提供更多的背景信息吗？你如何安装库，你正在使用什么机器，你试图调试它（如果有的话）。 Thanks 谢谢

I'm an idiot...I forget to read "read me",now I know why,thanks.

**Comment by vmoens** [comment]
v0.2.0 now includes wheels for M1!
Feel free to reopen if issues persist
