### ISSUE TITLE
[BUG] Interaction with matplotlib

### ISSUE THREAD

**Issue by matteobettini** [pytorch/rl#1604]
I am experiencing a strange issue where I am unable to visualise plots when importing torchrl

```python
from matplotlib import pyplot as plt

if __name__ == "__main__":
    # import torchrl  # if you uncomment this plt.show() does not block
    fig = plt.subplots()
    plt.show()
```

I have tried with multiple matplotlib versions and it seems happening in all.

**Comment by vmoens** [comment]
Works on macos with intel proc so my guess is that it's an M1 issue. Can you report the error message?
