### ISSUE TITLE
[BUG] Very minor correction to examples.md

### ISSUE THREAD

**Issue by maxweissenbacher** [pytorch/rl#1627]
## Describe the bug

In the examples.md file ([here](https://github.com/pytorch/rl/blob/main/examples/EXAMPLES.md)), the syntax provided to change the hyperparameters / environments etc. using hydra are not compatible with the syntax currently used in the yaml files. For instance, the examples.md document suggests to call

`python sac.py frames_per_batch=63`

However, this will lead to the following error (only part reproduced here)

`Key 'frames_per_batch' is not in struct`

In order to change the frame rate parameter, one needs to instead call

`python sac.py collector.frames_per_batch=63`

Same thing for the other examples in the document. This is obviously a very minor thing, but I thought I'd point it out in case someone gets around to changing it :-)

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Thanks for pointing this, it isn't minor at all! I will fix this
