### ISSUE TITLE
[BUG] Problems with `TanhNormal`

### ISSUE THREAD

**Issue by matteobettini** [pytorch/rl#1643]
## Describe the bug

I am using the `TanhNormal` class in my probabilistic policy, but I am getting some strange behaviors.
In my understanding the aim of that distribution is to take as input loc and scale from a neural network (with domains (-inf,inf) and [0,inf) respecitvely) and to create a probability disribution with sampling space [min,max].

Here is a script to elicidate my issue

```python
from torchrl.modules import TanhNormal
import torch
if __name__ == '__main__':
    print("Dist A: min -1, max 1, loc 40")
    scale = torch.tensor([1.])
    loc = torch.tensor([40])
    min = torch.tensor([-1])
    max = torch.tensor([1])
    dist = TanhNormal(loc=loc,scale=scale, min=min, max=max)
    print("Log prob at 40 ", dist.log_prob(torch.tensor([40.])))
    print("Log prob at 1 ", dist.log_prob(torch.tensor([1.])))
    print("Log prob at -1 ", dist.log_prob(torch.tensor([-1.])))
    print("Log prob at -40 ", dist.log_prob(torch.tensor([-40.])))
    # It seems like the distribution does not sum to 1


    print("\nDist B: min 35, max 45, loc 40")
    scale = torch.tensor([1.])
    loc = torch.tensor([40])
    min = torch.tensor([35])
    max = torch.tensor([45])
    dist = TanhNormal(loc=loc, scale=scale, min=min, max=max)
    print("Log prob at 200 ", dist.log_prob(torch.tensor([200.])))
    print("Log prob at 40 ", dist.log_prob(torch.tensor([40.])))
    print("Log prob at 1 ", dist.log_prob(torch.tensor([1.])))
    print("Log prob at -1 ", dist.log_prob(torch.tensor([-1.])))
    print("Log prob at -40 ", dist.log_prob(torch.tensor([-40.])))
    # I cannot understand the output here
```
```bash
Dist A: min -1, max 1, loc 40
Log prob at 40  tensor(-524.1652)
Log prob at 1  tensor(-524.1652)
Log prob at -1  tensor(-1103.9840)
Log prob at -40  tensor(-1103.9840)

Dist B: min 35, max 45, loc 40
Log prob at 200  tensor(-2635.8652)
Log prob at 40  tensor(-3202.5283)
Log prob at 1  tensor(-3795.5027)
Log prob at -1  tensor(-3795.5027)
Log prob at -40  tensor(-3795.5027)
```
In the second distribution it is even the case that 200 is more probable than 40 (the mean)

**Comment by vmoens** [comment]
That's expected I think. 
A few points:
- not sure what it means to get the log prob of 40 when the bounds are -1 to 1
- tanh normal can be concave or convex so the mean is almost never the mode and can be the less likely value

**Comment by vmoens** [comment]
Correction: the dist may not be concave but the mean and mode do not generally coincide.
Also be careful that the loc is not the mean, neither is tanh(loc). The mean is (by definition) the expected value and I'm not even sure it has a closed form value in the TanhNormal case.

**Comment by matteobettini** [comment]
Yeah my bad, I think I got confused because I was able to compute the log_prob in the OOD samples
