### ISSUE TITLE
[BUG] BoundedTensorSpec rand method always returns inf values with bounds (0, inf)

### ISSUE THREAD

**Issue by giorgiac98** [pytorch/rl#1652]
## Describe the bug

My env has an action spec like the following:
```python
Box(low=0, high=np.inf, shape=(5,), dtype=np.float32)
```
When I wrap my env with torchrl.envs.libs.gym.GymWrapper it creates a BoundedTensorSpec. Later in the code the rand method of BoundedTensorSpec is called and always returns an infinite action like:
```python
tensor([inf, inf, inf, inf, inf])
```

But this is not the expected behavior, I expect to get random values between 0 and inf. 

## To Reproduce

```python
import numpy as np
import torch
from torchrl.data.tensor_specs import BoundedTensorSpec
from gymnasium.spaces import Box

# the action spec I have in my env
spec = Box(low=0, high=np.inf, shape=(5,), dtype=np.float32)

# next lines are taken from torchrl/envs/libs/gym.py:273-292
device = 'cpu'
dtype = torch.float32
low = torch.tensor(spec.low, device=device, dtype=dtype)
high = torch.tensor(spec.high, device=device, dtype=dtype)
shape = spec.shape
t = BoundedTensorSpec(
                low,
                high,
                shape,
                dtype=dtype,
                device=device,
            )
print(t.rand(torch.Size([])))
```

## System info

 * Python version: Python 3.10.12
 * Torch version: 2.1.0
 * Gymnasium version: 0.28.1

```python
import torchrl, numpy, sys
print(torchrl.__version__, numpy.__version__, sys.version, sys.platform)
```
`0.2.0 1.25.1 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0] linux`

## Additional context
The code crashes in my env step function when it tries to standardise the action using the Scikit-learn Standard Scaler, it does not allow inf values. The rand method is called because I initialize the stats of the ObservationNorm transform (method init_stats of torchrl.envs.transforms.transforms.py line 2300).

## Reason and Possible fixes
The problem is how it calculates the random values in the BoundedTensorSpec class (torchrl.data.tensor_specs.py lines 1647-1659)
```python
a, b = self.space
if self.dtype in (torch.float, torch.double, torch.half):
    shape = [*shape, *self.shape]
    out = (
        torch.zeros(shape, dtype=self.dtype, device=self.device).uniform_()
        * (b - a)
        + a
    )
    if (out > b).any():
        out[out > b] = b.expand_as(out)[out > b]
    if (out < a).any():
        out[out < a] = a.expand_as(out)[out < a]
    return out
```
Given my action spec: a = 0 and b = inf, but this means it multiplies always by inf the output of the torch.zeros(..).uniform_().

## Checklist

- [X] I have checked that there is no similar issue in the repo (**required**)
- [X] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [X] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Oh yeah it must be because we do high - low!
I'll fix this immediately

**Comment by giorgiac98** [comment]
I had already tried to replace the inf value with the max representable value of float32 (in my case) but still the numbers generated were all close to the upper bound.
I changed the line of code I provided earlier in the thread to this:
```python
spec = Box(low=0, high=np.finfo(np.float32).max, shape=(5,), dtype=np.float32)
```
and the output was the following:
```python
tensor([3.6040e+37, 7.2179e+37, 3.0120e+38, 9.8736e+36, 2.2129e+38])
```
I tried to run the program multiple times and added a batch size to see if there was any difference but still numbers were all close to the upper bound. 

However, I think it's not a library problem anymore since I'm still having issues with those big numbers in my custom env, I'll need to fix this myself by analyzing the data and setting a correct upper bound for my problem.

Thank you very much for the quick fix anyway.

**Comment by vmoens** [comment]
I get if you generate a number uniformly at random between zero and a gazillion, chances are that you'll get a big number!
What value would you consider "reasonable"?

**Comment by giorgiac98** [comment]
Sorry for not making myself clear enough, the current behaviour is totally fine. The issue now lies in my custom env which I will need to work on it.

**Comment by vmoens** [comment]
Closing this issue as not planned but happy to reopen if there is cause for it
