### ISSUE TITLE
[BUG] TensorDict.where() got an unexpected keyword argument 'pad'

### ISSUE THREAD

**Issue by Jianye-Xu** [pytorch/rl#1656]
## Describe the bug

I encountered the following error when running the PyTorch official tutorial [MULTI-AGENT REINFORCEMENT LEARNING (PPO) WITH TORCHRL TUTORIAL](https://pytorch.org/rl/tutorials/multiagent_ppo.html):
`TensorDict.where() got an unexpected keyword argument 'pad'`

## To Reproduce

1. Open the PyTorch official tutorial [MULTI-AGENT REINFORCEMENT LEARNING (PPO) WITH TORCHRL TUTORIAL](https://pytorch.org/rl/tutorials/multiagent_ppo.html).
2. Click [Run in Google Colab](https://colab.research.google.com/github/pytorch/rl/blob/gh-pages/_downloads/a977047786179278d12b52546e1c0da8/multiagent_ppo.ipynb).
3. As instructed in the .ipynb file: _If you are running this in Google Colab, make sure you install the following dependencies_:
```python
!pip3 install torchrl
!pip3 install vmas==1.2.11
!pip3 install tqdm
```
4. Run all cells

## Expected behavior

All cells should be executed without errors.

## Screenshots

An error occurs when running to the line `for tensordict_data in collector:`:
<img width="945" alt="Screenshot 2023-10-26 at 11 48 01" src="https://github.com/pytorch/rl/assets/83649047/5711a645-36f9-470a-ae58-f07cac6bc1a8">
<img width="906" alt="Screenshot 2023-10-26 at 11 48 49" src="https://github.com/pytorch/rl/assets/83649047/c09682bf-d1cd-4fbf-bbde-35098590c886">

## System info
 * Platform: Google Colab
 * Python version: 3.10.12
 * gym: 0.25.2
 * tensordict: 0.2.0
 * torch: 2.1.0+cu118
 * torchrl: 0.2.1
 * tqdm: 4.66.1

## Additional context

None.

## Reason and Possible fixes
The exact line of code that caused this error can be located in the file `/usr/local/lib/python3.10/dist-packages/torchrl/envs/utils.py`:
```
node.where(~reset, other=node_reset, out=node, pad=0)
```
It seems that the function `where()` defined in `tensordict` does not accept the input argument `pad`. I looked into the local source code, and the definition of `where()` in both the class `TensorDict` and the class `TensorDictBase` is
```
def where(self, condition, other, *, out=None):
  ...   
  return
```
However, if I look into the [file from the GitHub of `tensordict`](https://github.com/pytorch/tensordict/blob/main/tensordict/tensordict.py), the definition looks like this:
```
def where(self, condition, other, *, out=None, pad=None):
  ...   
  return
```
 I don't know why they are different.

I tried to delete the argument `pad=0` and ran all cells again, but I got another error:
```
KeyError: 'key "loc" not found in TensorDict with keys [\'episode_reward\', \'info\', \'observation\']'
```
And I stopped here.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Yes I need to upload the tensordict wheels too, I was planning on doing that today!

**Comment by Jianye-Xu** [comment]
Thanks for the info! Running the code below in Google Colab fixed the error. 
```
!pip3 uninstall tensordict
!pip3 install tensordict-nightly
```

**Comment by vmoens** [comment]
This should be solved now!

**Comment by Jianye-Xu** [comment]
Thanks, it works now!
