### ISSUE TITLE
[BUG] Fix "done" instead of "terminated" mistakes

### ISSUE THREAD

**Issue by MarCnu** [pytorch/rl#1662]
## Describe the bug

I identified 3 mistakes that are most likely copy-pasting mistakes made during the large update to handle "terminated" on top of "done".

FIRST BUG: Twice an initialisation of terminated uses tensordict.get(done) which makes no sense.
```
done = tensordict.get(("next", self.tensor_keys.done))
terminated = tensordict.get(("next", self.tensor_keys.done), default=done)
```
tensordict.get(terminated, default=done) seems to be the correct pattern (it's present at several other locations of the file)
`terminated = tensordict.get(("next", self.tensor_keys.terminated), default=done)`

SECOND BUG: Once there is a function call of a with parameter "terminated=done" instead of the more logical "terminated=terminated".
```
            adv, value_target = vec_generalized_advantage_estimate(
                gamma,
                lmbda,
                value,
                next_value,
                reward,
                done=done,
                terminated=done,
```

I checked other uses of done and terminated but I couldn't spot more similar copy-pasting mistakes.

## To Reproduce

Not applicable

## Expected behavior

Not applicable

## Screenshots

Not applicable

## System info

Not applicable

## Additional context

Not applicable

## Reason and Possible fixes

Reason: Too much copy pasting

Fix: I sent a Pull Request.

https://github.com/pytorch/rl/pull/1661

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Thanks I'll push a fix soon!

**Comment by MarCnu** [comment]
I made a pull request in case you didn't see it.

**Comment by vmoens** [comment]
> I made a pull request in case you didn't see it.

Just saw that sorry I was looking at my log chronologically 😅
