### ISSUE TITLE
small bug in torchrl.envs.utils

### ISSUE THREAD

**Issue by Fauche** [pytorch/rl#1670]
Problem= no difference in the message printed when error about the shapes: fake vs real tensordict ...

in: torchrl.envs.utils
in the:  _per_level_env_check function
line: 394

actual code:
`if _data0.shape != _data1.shape:
                raise AssertionError(
                    f"The shapes of the real and fake tensordict don't match for key {key}. "
                    f"Got fake={_data0.shape} and real={_data0.shape}."
                )`

should be ( and proposed fix...):
`if _data0.shape != _data1.shape:
                raise AssertionError(
                    f"The shapes of the real and fake tensordict don't match for key {key}. "
                    f"Got fake={_data0.shape} and real={_data1.shape}."
                )`

This obviously has no impact on operation but can be confusing for those who encounter the error message…
Thanks for merging

**Comment by vmoens** [comment]
This has just been solved by #1669 I think
