### ISSUE TITLE
[Feature Request] V-D4RL datasets for offline RL.

### ISSUE THREAD

**Issue by conglu1997** [pytorch/rl#1674]
## Motivation

Alongside the D4RL datasets, it could be useful to have a pixel-based continuous control benchmark for offline RL integrated into this codebase. One such existing benchmark is V-D4RL with associated TMLR paper: [Challenges and Opportunities in Offline Reinforcement Learning from Visual Observations](https://arxiv.org/abs/2206.04779). This would naturally compliment the low-dimensional D4RL datasets and the proposed discrete action space Atari datasets.

I think this would be appropriate for the"call for contributions" stack. @vmoens 

## Solution

Integrate V-D4RL datasets from https://github.com/conglu1997/v-d4rl into `pytorch/rl`

## Checklist

- [X] I have checked that there is no similar issue in the repo (**required**)

**Comment by vmoens** [comment]
Added! Would you like to work on it?
