### ISSUE TITLE
Gen DGRL Dataset[Feature Request]

### ISSUE THREAD

**Issue by braj29** [pytorch/rl#1678]
## Motivation

Want to add the Gen DGRL Dataset for benchmarking RL algorithms in a easy & efficient way

## Solution

Use D4RL wrapper (https://github.com/Farama-Foundation/D4RL) to download and load the dataset ready for training using simple python commands

## Alternatives

For larger datasets it maybe best to download the files partially and then delete them as training progressing while simultaneously downloading remaining data

## Checklist

- [x] I have had an initial discussion with @vmoens 
- [ ] Get familiar with TorchRL and GenDGRL Dataset
- [ ] Create a wrapper to download and load the dataset

**Comment by vmoens** [comment]
Here too, I'd rather not use anything D4RL-based. The library is 100% unmaintained, and it's a disaster to install. I believe we have everything we need in-house to build this. Have a look at how torchvision does the data download and extraction, and feel free to copy paste parts of their code if needed!
https://github.com/pytorch/vision/tree/main/torchvision/datasets

**Comment by braj29** [comment]
Thanks a ton @vmoens ! I will take a look at how they have used torchvision datasets and do it that way

**Comment by vmoens** [comment]
Closed by #1773
