### ISSUE TITLE
[Question] Hidden key names treated differently from regular key names in tensordict

### ISSUE THREAD

**Issue by maxweissenbacher** [pytorch/rl#1709]
I have a question regarding the use of hidden keys in tensordict (i.e. a key name of the form `_keyname` rather than `keyname`).

In some code I am currently writing, it appears that these keys behave in different ways. Concretely, when I use a 'hidden' name like `_keyname`, an entry created by a TensorDictPrimer under this name (in this case, creating a memory for an agent) cannot be found in a rollout tensordict. The same issue does not occur when I use a 'regular' name like `keyname`.

If someone could explain the difference in treatment between 'hidden' and 'regular' key names to me that would be amazing!

Thanks

**Comment by vmoens** [comment]
Hi,
We exclude the private keys in the collectors to avoid polluting the replay buffer with useless data.
Imagine that I code a transformer using solely TensorDictModule and TensorDictSequential. If all the intermediate values are captured by the replay buffer it will be a lot of data that we may not need. 

This is controlled by the private attribute `controller._exclude_private_key`. If needed, I can make a PR to control that behaviour during construction!

Does that help?

**Comment by maxweissenbacher** [comment]
Hi Vincent,

Thank you for explaining! That makes a lot of sense. So a hidden key-value pair will not be copied into the replay buffer?

No need to change that behaviour - it makes a lot of sense, I just couldn't find any documentation on it.
