### ISSUE TITLE
Import error when running recently added 'discrete_cql_online.py' from examples/cql

### ISSUE THREAD

**Issue by spallaccini** [pytorch/rl#1725]
Hi, when attempting to run the example on the Discrete CQL algorithm (online) `discrete_cql_online.py` I experienced an import issue for the _DiscreteCQLLoss_ class from torchrl/objectives/utils.py.

Issue can be reproduced both running directly the script or isolating the import in a jupyter notebook as below:
`
from torchrl.objectives import CQLLoss, DiscreteCQLLoss, SoftUpdate`

> 
> ImportError                               Traceback (most recent call last)
> Cell In[1], line 1
> ----> 1 from torchrl.objectives import CQLLoss, DiscreteCQLLoss, SoftUpdate
> 
> ImportError: cannot import name 'DiscreteCQLLoss' from 'torchrl.objectives' 

I tried installing both torchrl and torchrl-nighly; other than this tiny issue the library is working perfectly for me.

The _CQLLoss_ class is correctly imported.

I found that the Discrete CQL had been recently added:
https://github.com/pytorch/rl/pull/1666

Thank you!

**Comment by vmoens** [comment]
can you print this
```
$ pip list | grep torchrl
```
You may have both torchrl and torchrl-nightly in your environment

**Comment by vmoens** [comment]
Second likely explanation: you're running the code from the `torchrl` root of the repo, but your git clone isn't updated, and when you run the script it tries to get a module that is not in the local directory.
If you're running it from `/path/to/rl` try to move somewhere else (eg, `/path/to/rl/examples/cql`)

I tried to reprod locally but couldn't. I also checked and the class is present and accessible in the nightlies on pypi...

**Comment by spallaccini** [comment]
Classification: Confidential
Actually I downloaded both utils.py and discrete_cql_online.py from git online and put them in a local folder prior to attempt running the example. I did not clone the whole repo.
Anyway I now tried to clone the rl repo and run the script as you instructed - keeping the pypi torchrl-nightly installed.

Result is the same, here is the printout (just pruned some paths):

***@***.***:~/TORCHRL/GITCLONE/rl/examples/cql$ python discrete_cql_online.py
UserWarning: Failed to import torchrl C++ binaries. Some modules (eg, prioritized replay buffers) may not work with your installation. If you installed TorchRL from PyPI, please report the bug on TorchRL github. If you installed TorchRL locally and/or in development mode, check that you have all the required compiling packages.
  warnings.warn(EXTENSION_WARNING)
Traceback (most recent call last):
  File ".../TORCHRL/GITCLONE/rl/examples/cql/discrete_cql_online.py", line 25, in <module>
    from utils import (
  File ".../TORCHRL/GITCLONE/rl/examples/cql/utils.py", line 35, in <module>
    from torchrl.objectives import CQLLoss, DiscreteCQLLoss, SoftUpdate
ImportError: cannot import name 'DiscreteCQLLoss' from 'torchrl.objectives' (.../lib/python3.11/site-packages/torchrl/objectives/__init__.py)
***@***.***:~/TORCHRL/GITCLONE/rl/examples/cql

The highlighted user warning was also there before
