### ISSUE TITLE
[BUG] Wrong Benchmark on Replaybuffer.

### ISSUE THREAD

**Issue by harnvo** [pytorch/rl#1759]
## Description

For some reason, the different replaybuffers, storages and samplers are not really tested in the benchmark. 
```
@pytest.mark.parametrize(
    "rb,storage,sampler,size",
    [
        [TensorDictReplayBuffer, ListStorage, RandomSampler, 4000],
        [TensorDictReplayBuffer, LazyMemmapStorage, RandomSampler, 10_000],
        [TensorDictReplayBuffer, LazyTensorStorage, RandomSampler, 10_000],
        [TensorDictReplayBuffer, ListStorage, SamplerWithoutReplacement, 4000],
        [TensorDictReplayBuffer, LazyMemmapStorage, SamplerWithoutReplacement, 10_000],
        [TensorDictReplayBuffer, LazyTensorStorage, SamplerWithoutReplacement, 10_000],
        [TensorDictPrioritizedReplayBuffer, ListStorage, None, 4000],
        [TensorDictPrioritizedReplayBuffer, LazyMemmapStorage, None, 10_000],
        [TensorDictPrioritizedReplayBuffer, LazyTensorStorage, None, 10_000],
    ],
)
def test_sample_rb(benchmark, rb, storage, sampler, size):
    (rb,), _ = create_rb(
        rb=TensorDictReplayBuffer,
        storage=ListStorage,
        sampler=RandomSampler,
        populated=True,
        size=size,
    )()
    benchmark(sample, rb)


```

As is shown in the code, only `TensorDictReplayBuffer` with `ListStorage` and `RandomSampler` is tested, and I believe this is not intended (since you wrote it in `parameterize`! )

## To Reproduce

```bash
python ./benchmarks/test_replaybuffer_benchmark.py
```

*Note: Need to install prerequisites within `rl/benchmarks/requirements.txt` to run the test.

## Expected behavior

Code does run successfully, but the benchmark is wrong. 
Actually, if you try to replace `rb=TensorDictReplayBuffer` in the `create_rb` with `rb=rb`, you expect to get the following error:

```terminal

FAILED benchmarks/test_replaybuffer_benchmark.py::test_sample_rb[TensorDictPrioritizedReplayBuffer-ListStorage-None-4000] - TypeError: __init__() got an unexpected keyword argument 'sampler'

```
And this is because we should not have argument `sampler` for `TensorDictPrioritizedReplayBuffer`, further evidencing that `TensorDictPrioritizedReplayBuffer` is never tested.

## System info

My environment:
 * Ubuntu 20.04.3 LTS
 * library was build from source
 * Python 3.9.0
 * `torch==2.1.2 torchrl==0.2.1+d125dd9 torchsnapshot==0.1.0 numpy==1.26.2`
 * `pytest==7.4.3 pytest-benchmark==4.0.0 pytest-instafail==0.5.0 tenacity==8.2.3`

## Reason and Possible fixes

For every initizalization of `create_rb`:
```python
    (rb,), _ = create_rb(
        rb=rb,
        storage=storage,
        sampler=sampler,
        populated=True,
        size=size,
    )()
```

at the import part:

```python

... Some other imports ...
# import partial for prb
from functools import partial

from torchrl.data import (
    ... some other imports ...
    TensorDictPrioritizedReplayBuffer,
    ......
)
from torchrl.data.replay_buffers import RandomSampler, SamplerWithoutReplacement

# default alpha and beta as it should not affect benchmark to much. 
# Note that This change the function name so this is not a elegant implementation. But this is sufficient for a quick fix.
TensorDictPrioritizedReplayBuffer = partial(TensorDictPrioritizedReplayBuffer, alpha=0.6, beta=0.4)
```

After this quick fix you do see a quite different ranking in benchmark.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
On it! Thanks for flagging
