### ISSUE TITLE
[BUG] Handling heterogeneous environment observations

### ISSUE THREAD

**Issue by ShaneFlandermeyer** [pytorch/rl#1767]
## Describe the bug

I am trying to implement an environment with set-valued observations of size N x K, where N is a set size that changes every step and K is static. Is there currently a "TorchRL approved" way of doing this? 

I see that this has been discussed a bit in https://github.com/pytorch/rl/issues/766. In particular, [this comment](https://github.com/pytorch/rl/issues/766#issuecomment-1373882180) shows an example in the simple_crypto vmas env which seems similar to my use case. However, I am having trouble accessing observations from the tensordict. It was also mentioned in https://github.com/pytorch/rl/issues/1343 that printing heterogeneous lazy stacks is annoying, so I'm mostly wondering if there has been any progress made since then. Thank you!

## To Reproduce
Generating a rollout works fine
```python
from torchrl.envs.libs.vmas import VmasEnv
env = VmasEnv("simple_crypto", num_envs=32)
td = env.rollout(10, return_contiguous=False)["agents"]
print(td)
```

```bash
LazyStackedTensorDict(
    fields={
        action: Tensor(shape=torch.Size([32, 10, 3, 6]), device=cpu, dtype=torch.float32, is_shared=False),
        observation: Tensor(shape=torch.Size([32, 10, 3, -1]), device=cpu, dtype=torch.float32, is_shared=False)},
    exclusive_fields={
    },
    batch_size=torch.Size([32, 10, 3]),
    device=cpu,
    is_shared=False,
    stack_dim=1)
```
Accessing the "normal way" fails with a reasonable error message

```python
print(td['observation'])
```

```bash
Traceback (most recent call last):
  File "/home/shane/anaconda3/envs/ml/lib/python3.9/site-packages/tensordict/tensordict.py", line 7030, in _get_str
    out = torch.stack(tensors, self.stack_dim)
RuntimeError: stack expects each tensor to be equal size, but got [32, 4] at entry 0 and [32, 8] at entry 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shane/anaconda3/envs/ml/lib/python3.9/site-packages/tensordict/tensordict.py", line 7495, in __getitem__
    return self._get_tuple(index_key, NO_DEFAULT)
  File "/home/shane/anaconda3/envs/ml/lib/python3.9/site-packages/tensordict/tensordict.py", line 7060, in _get_tuple
    first = self._get_str(key[0], None)
  File "/home/shane/anaconda3/envs/ml/lib/python3.9/site-packages/tensordict/utils.py", line 1131, in newfun
    return fun(_self, *args, **kwargs)
  File "/home/shane/anaconda3/envs/ml/lib/python3.9/site-packages/tensordict/tensordict.py", line 7019, in _get_str
    tensors.append(td._get_str(key, default=default))
  File "/home/shane/anaconda3/envs/ml/lib/python3.9/site-packages/tensordict/utils.py", line 1131, in newfun
    return fun(_self, *args, **kwargs)
  File "/home/shane/anaconda3/envs/ml/lib/python3.9/site-packages/tensordict/tensordict.py", line 7048, in _get_str
    raise RuntimeError(
RuntimeError: Found more than one unique shape in the tensors to be stacked ({torch.Size([32, 4]), torch.Size([32, 8])}). This is likely due to a modification of one of the stacked TensorDicts, where a key has been updated/created with an uncompatible shape. If the entries are intended to have a different shape, use the get_nestedtensor method instead.
```

But it also fails with ```get_nestedtensor()```

```python
td.get_nestedtensor('observation')
```

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/shane/anaconda3/envs/ml/lib/python3.9/site-packages/tensordict/tensordict.py", line 7201, in get_nestedtensor
    raise RuntimeError(
RuntimeError: Because nested tensors can only be stacked along their first dimension, LazyStackedTensorDict.get_nestedtensor can only be called when the stack_dim is 0.
```

## System info

Installed through pip

```python
import torchrl, numpy, sys
print(torchrl.__version__, numpy.__version__, sys.version, sys.platform)

0.2.1 1.26.2 3.9.17 (main, Jul  5 2023, 20:41:20) 
[GCC 11.2.0] linux
```

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by ShaneFlandermeyer** [comment]
I see the VMAS errors above have been fixed in the nightly package. However, advice would still be appreciated for observation spaces that vary on each step

**Comment by matteobettini** [comment]
Thanks for the comments! Here is my take on this.

The heterogeneity discussed in the comments you linked was within a single timestep. Heterogeneity through time is a little more tricky and I think the choice of not allowing it is deliberate. @vmoens maybe can say a few things about this

I think right now the only way to have an observation space with a shape that changes through time is using padding. I.e. you create the space of size Max_N x K. You can pad the non available observations with 0s or any other value of your choice. You can also output a mask among the obs, which tells what obs in the set are valid.

This is what we do for actions spaces with available actions changing through time. There, a mask is output by the env to make the specs know what actions are to be considered available. A similar thing could be done for obs.

This is similar to what we go in PettingZoo when there is a varying number of agents each step or the game is turn-based. You can check out the PettingZoo wrapper for more info on this.

**Comment by ShaneFlandermeyer** [comment]
> Thanks for the comments! Here is my take on this.
> 
> The heterogeneity discussed in the comments you linked was within a single timestep. Heterogeneity through time is a little more tricky and I think the choice of not allowing it is deliberate. @vmoens maybe can say a few things about this
> 
> I think right now the only way to have an observation space with a shape that changes through time is using padding. I.e. you create the space of size Max_N x K. You can pad the non available observations with 0s or any other value of your choice. You can also output a mask among the obs, which tells what obs in the set are valid.
> 
> This is what we do for actions spaces with available actions changing through time. There, a mask is output by the env to make the specs know what actions are to be considered available. A similar thing could be done for obs.
> 
> This is similar to what we go in PettingZoo when there is a varying number of agents each step or the game is turn-based. You can check out the PettingZoo wrapper for more info on this.
> 

Thank you! That's what I figured. This isn't a major problem for my application, so I'll close the issue now.
