### ISSUE TITLE
[BUG] Incorrect reward "clipping" in Atari baseline

### ISSUE THREAD

**Issue by skandermoalla** [pytorch/rl#1777]
The standard protocol in the DQN Atari Nature paper is to bin the rewards and not actually clip them, although typically called "reward clipping".
See https://github.com/openai/baselines/blob/ea25b9e8b234e6ee1bca43083f8f3cf974143998/baselines/common/atari_wrappers.py#L125 and https://iclr-blog-track.github.io/2022/03/25/ppo-implementation-details/

If the goal of the examples in TorchRL is to replicate this protocol then this https://github.com/pytorch/rl/blob/1874e9a23bde5be2c356b4bec90b5f0f9dcf4eaf/examples/ppo/utils_atari.py#L73 is not what is done in the "standard" protocol.

**Comment by albertbou92** [comment]
You are right!  Maybe a sign transforms would be necessary.
Although, in practice, are there any Atari environments with rewards smaller than +1/-1

**Comment by skandermoalla** [comment]
Good point! I didn't think at all if in practice this would actually be different.

**Comment by vmoens** [comment]
We should have a SignReward transform then I guess.
(Another example of bad naming conventions in RL...)

**Comment by vmoens** [comment]
@skandermoalla @albertbou92 do you guys want to code a `SignTransform` transform for this? I can maybe take care of it today or tomorrow, if you're not working on it atm

**Comment by albertbou92** [comment]
I am not working on it atm. I don't mind doing the PR on the side if you want to focus on other stuff. I will take longer than today/tomorrow though.

**Comment by skandermoalla** [comment]
Not working on it atm and unlikely to do so this week. Would be great if you took it. Thanks!

**Comment by albertbou92** [comment]
Added a `SignTransform` in https://github.com/pytorch/rl/pull/1798

**Comment by vmoens** [comment]
We need to adapt the scripts now I think

**Comment by albertbou92** [comment]
https://github.com/pytorch/rl/pull/1870
