### ISSUE TITLE
[BUG] The collector expands its container tensordict on the rollout device before moving it to the storing device.

### ISSUE THREAD

**Issue by skandermoalla** [pytorch/rl#1823]
Shouldn't this line https://github.com/pytorch/rl/blob/a10cdbfc3643fd10c14432ab0dfb89fc2326a755/torchrl/collectors/collectors.py#L675

appear after this line? https://github.com/pytorch/rl/blob/a10cdbfc3643fd10c14432ab0dfb89fc2326a755/torchrl/collectors/collectors.py#L681

Otherwise there is a peak of memory need on the device != storing_device defeating the purpose of a storing_device.

Also, somehow the memory is never garbage collected for me, and the pre-allocated tensor on the device is never freed.
This is also the case with the rollout collected from the ObservationNormTransform. I suspect there is something wrong with garbage collection of tensordicts, or I'm doing something wrong.

**Comment by vmoens** [comment]
Could be, which version of TensorDict are you using?

Can you detail a bit more when the mem should be collected and how you can tell it's not (for us to reproduce)?

**Comment by skandermoalla** [comment]
> Also, somehow the memory is never garbage collected for me, and the pre-allocated tensor on the device is never freed.
This is also the case with the rollout collected from the ObservationNormTransform. I suspect there is something wrong with garbage collection of tensordicts, or I'm going something wrong.

This is a bit out of scope for this issue. It was mainly as an argument here. I can open another one with more details about memory leak.

**Comment by vmoens** [comment]
I will work on the collector devices tomorrow and friday!
For the memory leak feel free to let me know if you can reproduce that in a simple script, it would be very useful to spot where that comes from and fix it!
