### ISSUE TITLE
[BUG] StepCounter overrides native truncation.

### ISSUE THREAD

**Issue by skandermoalla** [pytorch/rl#1837]
## Describe the bug
When one adds a step counter on a Gymnasium env with a max_step higher than the env's native limit (TimeLimit), the env is truncated at the native TimeLimit but the truncation key is overridden to False as not truncated by the step counter.

## To Reproduce

```python
from torchrl.collectors import SyncDataCollector
from torchrl.envs import StepCounter, TransformedEnv
from torchrl.envs.libs.gym import GymEnv

import gymnasium


N = 2000
env_id = "Acrobot-v1"
if __name__ == "__main__":
    env = GymEnv(env_id)
    env = TransformedEnv(env)
    # env.append_transform(StepCounter(max_steps=N, truncated_key="truncated"))

    collector = SyncDataCollector(env, policy=None, frames_per_batch=N + 10, total_frames=2 * N)
    b = collector.next()

    print(f'done: {b["next", "done"].squeeze(-1).nonzero().squeeze(-1)}')
    print(f'truncated: {b["next", "truncated"].squeeze(-1).nonzero().squeeze(-1)}')
    print(f'terminated: {b["next", "terminated"].squeeze(-1).nonzero().squeeze(-1)}')
```

Gives

```
done: tensor([ 499,  999, 1499, 1999])
truncated: tensor([ 499,  999, 1499, 1999])
terminated: tensor([], dtype=torch.int64)
```

Adding the step counter gives:

```
done: tensor([ 499,  999, 1499, 1999])
truncated: tensor([], dtype=torch.int64)
terminated: tensor([], dtype=torch.int64)
```

## Expected behavior

The StepCounter should read if a truncation key with the same name already exists.

## System info

```bash
torch                      2.2.0a0+81ea7a4
torchrl-nightly            2024.1.19
tensordict-nightly         2024.1.19
gymnasium                  0.29.1
```

**Comment by vmoens** [comment]
I think `env.env` should be `env._env`

if you do `env.env` GymEnv does not find it and falls back on your gym wrapper, gets its env (which is the order enforcing wrapper).

That is for the first part.

For step counter we should have something like `truncated = truncated | new_truncated`, but I think we simply override here. I can patch that easily I think.

**Comment by skandermoalla** [comment]
Ah yes! It's `._env` not `.env`! I'm updating the issue.

**Comment by skandermoalla** [comment]
Only the override is left then. I think it would be good not to override. What do you think?
You can argue that you should give a different truncation key to the StepCounter, but I wouldn't agree as both have the same semantic (why would you have 2 truncation keys?)
