### ISSUE TITLE
[BUG] UserWarning: Failed to import torchrl C++ binaries

### ISSUE THREAD

**Issue by wbinventor** [pytorch/rl#1888]
## Describe the bug

After installing TorchRL v0.3.0 from PyPi I am seeing the following warnings:

```bash
~/site-packages/torchrl/data/replay_buffers/samplers.py:37: UserWarning: Failed to import torchrl C++ binaries. Some modules (eg, prioritized replay buffers) may not work with your installation. If you installed TorchRL from PyPI, please report the bug on TorchRL github. If you installed TorchRL locally and/or in development mode, check that you have all the required compiling packages.
  warnings.warn(EXTENSION_WARNING)
```

## System info

This is running on Ubuntu 20 with Python v3.8.18. I installed `torchrl` as follows:

```bash
pip install torchrl
```

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Ah that isn't too good! In theory this should have been captured when building wheels... 
What machine are you using?
We'll be releasing a minor in a very short while so we can patch things up before then!

**Comment by bmanczak** [comment]
Don't know the exact reason for why this happens but when installed with force reinstall, with caching disabled it works:
`pip install --force-reinstal torchrl==0.3.0  --no-cache-dir`

**Comment by vmoens** [comment]
This `pip3 install torch==2.2 torchrl==0.3.0 torchvision==0.17` solved it for me on linux

**Comment by Saratii** [comment]
I can recreate this issue in fedora 40.
