### ISSUE TITLE
[Feature Request] Make `KLControllerBase` independent of the model

### ISSUE THREAD

**Issue by wbinventor** [pytorch/rl#1889]
## Motivation

Currently the `KLControllerBase` and in particular, its subclasses `ConstantKLController` and `AdaptiveKLController` require a model to provided to the constructor. The controller then updates a `kl_coef` instance attribute on the model in addition to updating an attribute with the same value on the controller itself: https://github.com/pytorch/rl/blob/4d52d5ffe085aff01d6eee6d3e901aa25d4c7561/torchrl/data/rlhf/utils.py#L49-L56

Is there a reason that the controller needs a model? If not, can the model be removed or made optional? It seems to me that the controller can be made completely independent of the model.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

**Comment by vmoens** [comment]
I agree, wrappers are the worst. I'll dig into this, there are multiple wrappers I want to get rid of or refactor into regular modules that you can put in a list. I'll keep you posted on the progress!
