### ISSUE TITLE
[Feature Request] Expose `time_dim` parameter on `GAE` and other advantage estimators

### ISSUE THREAD

**Issue by wbinventor** [pytorch/rl#1915]
The functional advantage estimators such as [`generalized_advangate_estimate`](https://pytorch.org/rl/reference/generated/torchrl.objectives.value.functional.generalized_advantage_estimate.html) have a `time_dim` kwarg. The object-oriented interface for advantage estimation deduces `time_dim` as `tensordict.ndim - 1`. It would be nice to expose this `time_dim` as a parameter on `GAE` and other objects for advantage estimation. This is relevant for some use cases where it may not be convenient/possible to represent all tensors in the input tensordict with the same time dimension.

**Comment by vmoens** [comment]
You're absolutely right.
There are 2 things we can do:
1. Use the names of the dimensions that is supported by tensordict to indicate what the time dimension is
2. do exactly as you say if the time dimension is not marked and default to `tensordict.ndim-1` if no dim is passed.
I'll make a PR with this shortly!
