### ISSUE TITLE
[BUG] Dev install requires nonexistent tensordict version

### ISSUE THREAD

**Issue by Jex-y** [pytorch/rl#1949]
## Describe the bug

in setup.py:173 tensordict>=0.4.0 is required, however only up to version 0.3.0 is available.

## To Reproduce

```bash
$ git clone git@github.com:pytorch/rl.git
$ cd rl
$ pip install -U ninja
$ python setup.py develop
Searching for tensordict>=0.4.0
Reading https://pypi.org/simple/tensordict/
No local packages or working download links found for tensordict>=0.4.0
error: Could not find suitable distribution for Requirement.parse('tensordict>=0.4.0')
```

## Expected behavior

torchrl requires tensordict>=0.3.0 and installs correctly

## Reason and Possible fixes

Possibly a typo in the version number. 

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by Jex-y** [comment]
Looking at the tensordict repo it appears that the source has version 0.4.0 but this hasn't been pushed to pypi yet.

**Comment by vmoens** [comment]
Yes we develop both libs in parallel so if you're using the dev version of rl you need the dev version of PyTorch and TensorDict!
