### ISSUE TITLE
[Distributed Training]

### ISSUE THREAD

**Issue by sgfCrazy** [pytorch/rl#2022]
## Motivation

Hello, I am using the distributed training module of torchrl. I successfully ran the generic.py script in examples/distributed/collectors, but I couldn't find a complete example of distributed training. Could you please provide a complete example of distributed training? Also, I would like to ask, during data collection, does the operation of executing forward inference to get actions by the policy network occur on the data collection node? If so, does it mean that the data collection node must also have a GPU when the policy network is large?Looking forward to your response, thank you.

## Solution
I need a complete example of distributed training. 

## Checklist

- [yes ] I have checked that there is no similar issue in the repo (**required**)

**Comment by vmoens** [comment]
Sorry for the late reply, just saw that you closed this issue.
Happy that you've found the resources you need :) 
Let us know if you still need more resources about this!
