### ISSUE TITLE
Achieving Episode-Based Sampling with SliceSampler in TorchRL

### ISSUE THREAD

**Issue by plspeziali** [pytorch/rl#2056]
In our project, we're employing a SliceSampler to aggregate our training trajectories into a ReplayBuffer. Our primary objective when sampling from this ReplayBuffer is to ensure that the sampled slices commence from the beginning of each episode.

Upon reviewing the [documentation of the SliceSampler](https://pytorch.org/rl/reference/generated/torchrl.data.replay_buffers.SliceSampler.html), we noted a reference to a start signal in relation to the `cache_values` parameter.

Now the question arises: does this feature align with our requirement? If so, how can we effectively harness it to achieve our desired outcome? Conversely, if it doesn't serve our purpose, are there alternative methods within TorchRL that we can explore to accomplish our goal?

Thank you.

**Comment by vmoens** [comment]
Hey!
Let's take a concrete example: if you have trajectories of length 10, 15 and 20 in your buffer and you want samples of length 12, you could:
- sample anything greater than 20
- use split_trajectories to separate the trajectories from each other in a [B,T] format
- take the first 12 elements

Would that work?

Both utils (split_trajectories and SliceSampler) have had significant developments lately so you may want to use the nightlies for your project.

**Comment by plspeziali** [comment]
We are now doing as you suggested, thank you very much :)
