### ISSUE TITLE
Tutorial of implementing learning using torchrl in a PettingZoo environment

### ISSUE THREAD

**Issue by AnastasiaPsarou** [pytorch/rl#2067]
Is there a tutorial on how to implement an RL algorithm like PPO in a PettingZoo env using TorchRL. I used the PettingZooWrapper() function on the already created environment but after that I am confused on how to procede further.

**Comment by vmoens** [comment]
Hello!
I think this is the purpose of https://github.com/pytorch/rl/pull/2047 but @matteobettini will be the person to confirm

**Comment by matteobettini** [comment]
It is indeed!

**Comment by matteobettini** [comment]
Does this https://pytorch.org/rl/stable/tutorials/multiagent_competitive_ddpg.html solve your issue?

**Comment by vmoens** [comment]
I believe this is solved now thanks to Matteo's amazing tuto, happy to reopen if needed
