### ISSUE TITLE
[BUG] default snapshot backend doesn't match docs

### ISSUE THREAD

**Issue by jannessm** [pytorch/rl#2075]
## Describe the bug

The [documentation](https://pytorch.org/rl/reference/trainers.html#checkpointing) doesn't match its [implementation](https://github.com/pytorch/rl/blob/main/torchrl/_utils.py#L197).

When using the trainer as described, the trainer cannot save a checkpoint since the provided path is a directory and not a file.

## To Reproduce

Try to use the trainer with `save_file_file = './ckpts'`. Of course the directory must exist.

## Expected behavior

Saved checkpoints by torchsnapshot.

**Comment by vmoens** [comment]
I will correct this thanks for flagging.
