### ISSUE TITLE
[Feature Request] Move `sota-check` inside `sota-implementations`

### ISSUE THREAD

**Issue by matteobettini** [pytorch/rl#2077]
The `sota-check`  folder essentially contains scripts used by maintainers to run the algos in `sota-implementations`.

I think moving it inside that folder provides a clearer library root structure and highlights their correlation

cc @albertbou92

**Comment by matteobettini** [comment]
In addition I would rename `sota-implementations/SOTA-IMPLEMENTATIONS.md` -> `sota-implementations/README.md` cause currently its contents are not displaying on github

**Comment by albertbou92** [comment]
Alternatively we could also move it to `tests`? at the end we use it as a manual test

**Comment by matteobettini** [comment]
If that does not interfere with pytest syntax and the users would have no benefit from running `sota-check` it could make sense

**Comment by vmoens** [comment]
Tests is solely for tests run in the CI and I would prefer to keep it separated from anything else.

Neither tests nor sota runs are private features and hence they are user facing - users can care about them.

We can move it to sota-implementations, my only concern is that it'll be a folder that doesn't align with all other folders in the same directory - this is why we put it separately in the first place. 

What is the issue with having it at the root?

**Comment by matteobettini** [comment]
> What is the issue with having it at the root?

Basically the ones I explain in the description of the issue.

I find it confusing and not very helpful to the users as it drives away attention to the more useful sota-implementations folder.

**Comment by vmoens** [comment]
I could argue the opposite: if you walk through sota-implementations, having one and just one folder that isn't an algorithm name may be confusing too

**Comment by matteobettini** [comment]
Sure i ll close then



> In addition I would rename `sota-implementations/SOTA-IMPLEMENTATIONS.md` -> `sota-implementations/README.md` cause currently its contents are not displaying on github

maybe let's still do this though

**Comment by vmoens** [comment]
Sure that should be easy enough for anyone from the community to do ;)
