### ISSUE TITLE
[BUG] VSCode automcompletions don't work

### ISSUE THREAD

**Issue by GJBoth** [pytorch/rl#2095]
Hi, I'm running VSCode with pylance as editor and the autocompletes don't work for some reason. It finds `torchrl.envs` for example, but when I import `CatTensors` for example it can't find the definition. Important to note that the script runs fine so python is able to import everything, and using the Jedi language server works, so its something to do with pylance.

Pylance: v2024.4.1
VSCode: 1.88.0 
torchrl: 0.3.1

Below a screenshot - 
<img width="232" alt="Screenshot 2024-04-22 at 10 13 50 AM" src="https://github.com/pytorch/rl/assets/32122273/0b48a4a8-a48a-4fe5-a606-029a6043d70e">

**Comment by GJBoth** [comment]
Some further investigation revealed a buggy pyright config. Sorry for bothering!

**Comment by vmoens** [comment]
No worry :)
