### ISSUE TITLE
[BUG] `ConvNet` memory issues

### ISSUE THREAD

**Issue by matteobettini** [pytorch/rl#2100]
Hello! 

I am having a particularly strange bug when using `ConvNet`.

Basically the module hangs on forever requesting an increasing amount of memory when called with data of a high size

```python
import torch
import torchrl
import sys

input = torch.rand((1, 1000, 7, 3, 88, 88), dtype=torch.float32)
print(sys.getsizeof(input.storage())/ 1_000_000, " MB") # This prints 650.496048  MB

net = torchrl.modules.ConvNet(in_features=3)

net(input) # This hangs on forvever allocating > 32GB of memory and increasing
```

I have tried it on my Macbook M1 with torchrl main and on colab with 0.3.1.

Particularly I do not undersand why the forward pass has this increasing memory requirement which asks for more than 30GB (crashing on colab and my computer)

cc @ezhang7423

**Comment by ezhang7423** [comment]
I got the same issue on Linux with 32 GB of RAM.

**Comment by vmoens** [comment]
The output of this network is of size [1, 1000, 7, 215168] which is about 48Gb

```python
import torch
import torchrl
import sys

input = torch.rand((1, 1000, 7, 3, 88, 88), dtype=torch.float32, device="meta")
print(sys.getsizeof(input.storage())/ 1_000_000, " MB") # This prints 650.496048  MB

net = torchrl.modules.ConvNet(in_features=3)
print(net(input).shape)
```

**Comment by matteobettini** [comment]
He did you get 48Gb? 

I am getting that it should be 6Gb 

```python
output = torch.rand((1, 1000, 7, 215168), dtype=torch.float32)
print(sys.getsizeof(output.storage()) / 1_000_000, " MB") # 6024.704048  MB
```

**Comment by matteobettini** [comment]
Got it. Thanks a lot for this!
