### ISSUE TITLE
[BUG] Done/Reset not initiated when using PettingZooWrapper with Custom PettingZoo environment

### ISSUE THREAD

**Issue by mchoilab** [pytorch/rl#2138]
## Describe the bug

I followed the custom pettingzoo parallel env creation guideline [https://pettingzoo.farama.org/content/environment_creation/#example-custom-parallel-environment](https://pettingzoo.farama.org/content/environment_creation/#example-custom-parallel-environment)

and wrapped with pettingzoowrapper. It seems like the done or env_truncation/terminations/truncations are not passed correctly when wrapped.

Reset function is never called after terminations= true, truncations = true. 

When my environment was "done", it returns 

`        if env_truncation:
            self.agents = []
`
which I followed the pettingzoo env creation guideline 

## To Reproduce

please refer to this colab notebook: 

https://colab.research.google.com/gist/mchoilab/0bc43674f9234efd10dd281579e15abb/torchrl_custompettingzoo.ipynb

## Expected behavior

Reset function to be called after terminations= true, truncations = true. 

## System info

 * Python version (local machine: 3.8.19 / google colab default)
 * torchrl 0.4.0

## Reason and Possible fixes

because  of self.agents = [] when done, this seems to crash with [line 686 in pettingzoo.py](https://github.com/pytorch/rl/blob/3c6b9c6eaf106ef50bd859a12cae3c0c89249d34/torchrl/envs/libs/pettingzoo.py#L686) 

## Checklist

- [ checked ] I have checked that there is no similar issue in the repo (**required**)
- [ checked  ] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [ checked  ] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by matteobettini** [comment]
In the section when you remove `self.agents = []`, if i run `env.rollout(max_steps=10_000, break_when_any_done=False)` i see the environement resetting

**Comment by matteobettini** [comment]
and this works also in the case you keep `self.agents = []`

**Comment by matteobettini** [comment]
Maybe there is a confusion stemming from how the rollout function works:

- `env.rollout(max_steps=10_000, break_when_any_done=False)` will reset after every done and reach max_steps
- `env.rollout(max_steps=10_000, break_when_any_done=True)` will reach the first done or max_steps and break without resetting

**Comment by matteobettini** [comment]
We can move the discussion to benchmarl if there is no issue in torchrl.

Basically I think that the benchmarl issue should be solved if you remove the `self.agents =[]`.

Could you confirm that this is the case?
