### ISSUE TITLE
[BUG] TruncatedNormal returns wrong values in case of asymmetric bounds 

### ISSUE THREAD

**Issue by ITWARRIORS-Kilian** [pytorch/rl#2146]
# TruncatedNormal returns wrong values in case of asymmetric bounds 
## Describe the bug

When using asymmetric around 0 bounds like 'min = -1' and 'max = 2'  the code returns the wrong logarithm of the probability density. It also seems to sample incorrectly in this case. 

Below you can find code calculating and plotting the probability density function of a truncated normal distribution with location ('loc') 0 and sigma ('scale') 1:

![image](https://github.com/pytorch/rl/assets/4347891/19715f2c-0ac9-4e06-b71c-0f6e7341e98e)

As the figure shows the density function calculated using torchrl.modules.distributions.TruncatedNormal results in a distribution with a wrong location (see the blue, not dashed line) while using scipy results in the correct distribution as defined in "The Truncated Normal Distribution" by John Burkardt (see Figure 15 in https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf) - This paper is also cited in the code.

## To Reproduce

Steps to reproduce the behavior.

Please try to provide a minimal example to reproduce the bug. Error messages and stack traces are also helpful.

Please use the markdown code blocks for both code and stack traces.

```python
import torchrl
import torch
import matplotlib.pyplot as plt
from scipy.stats import truncnorm as sp_truncnorm

#torchrl version
x = torch.linspace(-1.5, 2.5, 1000).view(-1, 1, 1)
mu = torch.tensor([0.], requires_grad=True)
sigma = torch.tensor([1.], requires_grad=True)
log_pi_x = torchrl.modules.distributions.TruncatedNormal(mu, sigma, min=-1, max=2, tanh_loc=False, upscale=20).log_prob(x)
pi_x = torch.exp(log_pi_x)
log_pi_x.backward(torch.ones_like(log_pi_x))
#plot pi_x
x_numpy = x.view(-1).detach().numpy()
pi_x_numpy = pi_x.view(-1).detach().numpy()
fig, ax = plt.subplots()
ax.plot(x_numpy, pi_x_numpy, label='torchrl')
# add vertical line at x=0.5
ax.axvline(x=0, color='r')
ax.grid()
# scipy version
a = 0.02
sigma = 1
mu = 0
U, L = (2 - mu) / sigma, (-1 - mu) / sigma
scipy_truncnorm = sp_truncnorm(L, U, loc=mu, scale=sigma)
pdf_scypi_truncnorm = scipy_truncnorm.pdf(x_numpy)
#plot pdf_scypi_truncnorm
ax.plot(x_numpy, pdf_scypi_truncnorm, '--',label='scipy')
ax.legend()
```

## Expected behavior

Output of torchrl version should be identical to scipy version.

## System info

Describe the characteristic of your environment:
 * Describe how the library was installed (pip, source, ...)
 * Python version
 * Versions of any other relevant libraries

```python
import torchrl, numpy, sys
print(torchrl.__version__, numpy.__version__, sys.version, sys.platform)
```

results in:

```
0.4.0 1.25.2 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:38:37) [MSC v.1916 64 bit (AMD64)] win32
```

## Reason and Possible fixes

Playing a bit with the code it seems that the correct output can be obtained by subtracting the middle point of the bound range from the location parameter:

'loc_mod = loc + min + 0.5*(max-min)'

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Thanks for flagging this, let me have a look!
The code came from a repo implementing truncated normal for PyTorch - we should have checked better!
