### ISSUE TITLE
[Question] Only Windows distribution when version>=2024.6.24

### ISSUE THREAD

**Issue by wertyuilife2** [pytorch/rl#2254]
torchrl-nightly>=2024.6.24 on https://pypi.org/project/torchrl-nightly only has distribution files for Windows, but none for Linux. 

When using `pip install torchrl-nightly` on linux, the latest version found is only 2024.6.23. Is there a Linux version available?

**Comment by vmoens** [comment]
Solved!
https://pypi.org/project/torchrl-nightly/#history
