### ISSUE TITLE
[Feature Request] Allow custom video settings to be passed into `CSVExperiment.add_video`

### ISSUE THREAD

**Issue by N00bcak** [pytorch/rl#2258]
## Motivation

Please outline the motivation for the proposal.
Is your feature request related to a problem? e.g., "I'm always frustrated when [...]".
If this is related to another issue, please link here too.

### NOTE: This relates to a personal issue encountered with a custom TorchRL environment which has a **known good** render function.

Currently, `VideoRecorder` (and its downstream logger `CSVLogger`) does not allow for custom video settings to be passed when dumping environment rollouts (via `pyAV`/`torchvision`)

These video settings are actually `FFmpeg` settings which may have undesirable defaults from `pyAV`/`torchvision`, resulting in blurry/low-quality videos.

Among the various other reasons there may be to play with the video dumping settings, it may conversely be desirable to lower the visual fidelity of the video for better performance.

## Solution

Expose `kwargs` in `CSVExperiment.add_video` to `torchvision.io.write_video`, allowing end-user to pass FFmpeg `kwargs` when recording rollouts.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

**Comment by vmoens** [comment]
I think this is solved now
