### ISSUE TITLE
[Feature Request] Document masks in tensor specs

### ISSUE THREAD

**Issue by vmoens** [pytorch/rl#2280]
Various classes in the specs have the `"mask"` entry undocumented:
- https://github.com/pytorch/rl/blob/533d3f93aa55a4044a6e337448957f92f129d490/torchrl/data/tensor_specs.py#L1297
- https://github.com/pytorch/rl/blob/533d3f93aa55a4044a6e337448957f92f129d490/torchrl/data/tensor_specs.py#L2505
- https://github.com/pytorch/rl/blob/533d3f93aa55a4044a6e337448957f92f129d490/torchrl/data/tensor_specs.py#L2880
- https://github.com/pytorch/rl/blob/533d3f93aa55a4044a6e337448957f92f129d490/torchrl/data/tensor_specs.py#L3304

The docstrings should explain that this mask can be set to hide part of the discrete specs to hide part of the domain.
The docstrings should also explain how the mask can be updated (using `spec.update_mask`).
An example should be provided with the mask. See the tests to understand how the mask is used: https://github.com/pytorch/rl/blob/533d3f93aa55a4044a6e337448957f92f129d490/test/test_specs.py#L3460

@kurtamohler is it something you could help with?

**Comment by kurtamohler** [comment]
> @kurtamohler is it something you could help with?

Sure thing!
