### ISSUE TITLE
[Feature Request] Make GymLikeEnv compatible with IsaacLab Envs

### ISSUE THREAD

**Issue by yu-fz** [pytorch/rl#2369]
## Motivation

The current implementation of `GymLikeEnv._step(...)` is incompatible with IsaacLab environments due to the conversion to numpy when IsaacLab expects a torch tensor:

```
    def _step(self, tensordict: TensorDictBase) -> TensorDictBase:
        action = tensordict.get(self.action_key)
        action_np = self.read_action(action)
        reward = 0
        for _ in range(self.wrapper_frame_skip):
            (
                obs,
                _reward,
                terminated,
                truncated,
                done,
                info_dict,
            ) = self._output_transform(self._env.step(action_np))
```

## Solution

Perhaps we can add a config parameter to `GymLikeEnv` to specify if the underlying environment uses either `np.ndarray` or `torch.tensor` types. 

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

**Comment by vmoens** [comment]
Sure I'll work on that!
