### ISSUE TITLE
[BUG] dumps() failing on ReplayBuffer with LazyMemmapStorage

### ISSUE THREAD

**Issue by kalyan0510** [pytorch/rl#2390]
## Describe the bug

Calling dumps(path) on ReplayBuffer with LazyMemmapStorage fails with an error.   
cause: `replay_buffer._storage._storage.saved_path` seems to be set to None.

## To Reproduce

Steps to reproduce the behavior.
Execute the example code provided in the doc for [ReplayBuffer:dumps()](https://pytorch.org/rl/main/_modules/torchrl/data/replay_buffers/replay_buffers.html#ReplayBuffer.dumps)
or this code
```python
import os

import torch
from tensordict import TensorDict
from torchrl.data import TensorDictReplayBuffer, LazyMemmapStorage, ReplayBuffer

replay_buffer = ReplayBuffer(
    storage=LazyMemmapStorage(10000),
    prefetch=None,
    batch_size=40,
    pin_memory=True)

replay_buffer.extend(TensorDict({
        'actions': torch.ones(10,10,10, dtype=torch.int32),
    }, batch_size=[10]))

print(replay_buffer.storage._storage.saved_path) # None
replay_buffer.dumps(path='/home/kalyan/tmp')
replay_buffer.dumps(path=os.path.join('/home/kalyan/tmp'))
```

```bash
None
Traceback (most recent call last):
  File "/home/kalyan/.config/JetBrains/PyCharm2024.1/scratches/screatch5.py", line 18, in <module>
    replay_buffer.dumps(path='/home/kalyan/tmp')
  File "/home/kalyan/anaconda3/envs/rlostrack/lib/python3.8/site-packages/torchrl/data/replay_buffers/replay_buffers.py", line 465, in dumps
    self._storage.dumps(path / "storage")
  File "/home/kalyan/anaconda3/envs/rlostrack/lib/python3.8/site-packages/torchrl/data/replay_buffers/storages.py", line 97, in dumps
    self.checkpointer.dumps(self, path)
  File "/home/kalyan/anaconda3/envs/rlostrack/lib/python3.8/site-packages/torchrl/data/replay_buffers/checkpointers.py", line 96, in dumps
    and Path(_storage.saved_path).absolute() == Path(path).absolute()
  File "/home/kalyan/anaconda3/envs/rlostrack/lib/python3.8/pathlib.py", line 1042, in __new__
    self = cls._from_parts(args, init=False)
  File "/home/kalyan/anaconda3/envs/rlostrack/lib/python3.8/pathlib.py", line 683, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "/home/kalyan/anaconda3/envs/rlostrack/lib/python3.8/pathlib.py", line 667, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

## Expected behavior

save the rb

## System info

```python
import torchrl, numpy, sys
print(torchrl.__version__, numpy.__version__, sys.version, sys.platform)
0.5.0 1.24.4 3.8.19 | packaged by conda-forge | (default, Mar 20 2024, 12:47:35)
[GCC 12.3.0] linux

tensordict.__version__ = 0.5.0 (installed from nightly)
```

## Reason and Possible fixes

When storage init with scratch dir, it fixed the problem
`LazyMemmapStorage(10000, scratch_dir='/home/kalyan/tmp')`

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by N00bcak** [comment]
Hi,

[The fix](https://github.com/pytorch/rl/pull/2343) is already in the latest `main`. You might want to check your nightly build's source code to see if the fix is already present:
https://github.com/pytorch/rl/blob/bb0ddb5e3397df10ca7bd22145135b1b9ae3f3a1/torchrl/data/replay_buffers/checkpointers.py#L96-L98
