### ISSUE TITLE
[BUG] TensorDictReplayBuffer's pin_memory=True does not work with custom transforms

### ISSUE THREAD

**Issue by kalyan0510** [pytorch/rl#2404]
## Describe the bug

`TensorDictReplayBuffer`'s `pin_memory=True` does not work with custom transforms 

```python
rb = TensorDictReplayBuffer(storage, pin_memory=True, transform=CustomTransform())
rb.sample()['actions'].is_pinned() # False
```

## To Reproduce

```python
import torch
from torchrl.data import LazyMemmapStorage, TensorDictReplayBuffer
from tensordict import TensorDict


class CustomTransform:
    def __call__(self, tensordict: TensorDict) -> TensorDict:
        output = TensorDict({'observation': tensordict['observation']}, batch_size=10)
        return output


rb = TensorDictReplayBuffer(storage=LazyMemmapStorage(1000, scratch_dir='/tmp'), pin_memory=True,
                            transform=CustomTransform())

for i in range(100):
    td = TensorDict({"observation": torch.randn(10, 4)}, batch_size=[10])
    rb.add(td)

sample = rb.sample(10)

print(sample['observation'].is_pinned())  # False, expecting True

```

## Expected behavior

Expecting the samples to be memory pinned.

## System info

```python
import torchrl, numpy, sys
print(torchrl.__version__, numpy.__version__, sys.version, sys.platform)
0.5.0 1.24.4 3.8.19 | packaged by conda-forge | (default, Mar 20 2024, 12:47:35)
[GCC 12.3.0] linux

tensordict.__version__ = 0.5.0 (installed from nightly)
```

## Reason and Possible fixes

When a new TensorDict is created (`output = TensorDict({'observation': tensordict['observation']}, batch_size=10)`) its `device` property is set to None, unless specified.
At [torchrl/data/replay_buffers/utils.py#L88](https://github.com/pytorch/rl/blob/main/torchrl/data/replay_buffers/utils.py#L88), the sampled data is skipped from pinning, because its `.device` is None. 

I have various thoughts about this. 
- is this expected behavior? (It actually took me a while to figure out I should set device='cpu')
- should the `output.device==torch.device('cpu')` check exist? I just looked at `torch`'s pin_memory() method. There the input is not expected to be in 'cpu'.
- instead should there be a check whether all tensors in the TensorDict are in cpu?

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Good catch, we should move the decorator from `_sample` to `sample` here:
https://github.com/pytorch/rl/blob/e82a69f5af94cc936c4b872fd2ed499ed33b4f8e/torchrl/data/replay_buffers/replay_buffers.py#L655-L679
Note that this pin-memory implementation isn't very smart, see https://pytorch.org/tutorials/intermediate/pinmem_nonblock.html#:~:text=Importantly%2C%20pin_memory%20is%20blocking%20on,ones()%20and%20other%20constructors.
