### ISSUE TITLE
[Feature Request] aarch64-linux wheels

### ISSUE THREAD

**Issue by fabian1heinrich** [pytorch/rl#2430]
## Motivation

TorchRL doesn't provide any wheels for aarch64 linux. Sometimes I need to work on my MacBook and I would like to use my GitHub codespaces devcontainer configs again.

Furthermore, if I try to install it by referring to the repo the installation fails
```bash
poetry add git+https://github.com/pytorch/rl.git
```

Installing tensordict with the same method works though

```bash
poetry add git+https://github.com/pytorch/tensordict.git
```

## Solution

Provide aarch64 linux wheels

## Additional context

I use the mcr.microsoft.com/devcontainers/python:3.12 devcontainer

**Comment by vmoens** [comment]
Makes sense, let me see what I can do!
