### ISSUE TITLE
[Feature Request] Done signals as input keys

### ISSUE THREAD

**Issue by tommasomarzi** [pytorch/rl#2432]
## Motivation

Thanks for your amazing work!

In some RL problems (e.g., hierarchical RL), done signals may be necessary for the policy to generate internal inputs asynchronously. For example, in a two-level hierarchy, the upper level may have to propagate inputs to the lower level every N steps, where each time the environment is reset, the step count is also reset. In this case, if one of the batch_size environments is done, the associated propagation step needs to be set to zero, i.e., at the next step the upper level must propagate a new input to the lower one.

## Solution

A possible solution can be achieved with two changes in the `_make_compatible_policy` and `rollout` functions (I'm working with `break_when_any_done=False`).

- for the first one, it should be sufficient to make the input keys of `_make_compatible_policies` parametric: in this way, the policy possibly also accepts a `done` key.

- the second one is related to the tensors generated in the `step_and_maybe_reset` function: we need to combine the new observations with possible reset (`tensordict_['observation']`) and the done signals before the reset (`tensordict['next']['done']`) in a new TensorDict, which is then given as input to the policy. This is needed because the `maybe_reset` function resets the done environment and sets the associated done signals of `tensordict_` to False.

## Alternatives

For the first change, one option would be to transform the observation key in a nested dictionary and add the done signals, but that seems a bit counterintuitive to me... Also, I'm not sure if it's possible to achieve the same goal changing the observation space using a torchrl transform.

## Additional context

I'm working with a VMAS environment and using the `rollout` function with `break_when_any_done=False` to generate rollouts.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

@matteobettini

**Comment by vmoens** [comment]
Thanks for the kind words!

I'd be very happy to help but I have a limited understanding of what the problem is, precisely.

Can you point me to a piece of code that currently breaks, or an example of what you'd like to achieve? 
For instance, 
> the rollout below has output X but we would also like to see the field Y representing Z
or 
> I would like a transform that carries the done state from one step to the other (?)

There seems to be a list of feature requests here, and I'd love to help with each of them. I think a bunch can already be supported by the tooling we have, maybe not all...

**Comment by tommasomarzi** [comment]
Thanks for the quick replies!

> It seems that your problem is for the policy to be able to read the "done" key coming from batched env.

Yes, that was exactly what I was looking for! The `InitTracker`transform solves the problem.

> PS: we have a similar transform for counting steps

Awesome, I'll combine it with `InitTracker`.

Thanks again for your help!

**Comment by matteobettini** [comment]
You can’t just use the StepCounter transform and check when steps are 0 without the need for InitTracker

**Comment by vmoens** [comment]
Can or can't?

**Comment by matteobettini** [comment]
Uups, typo, corrected now

**Comment by tommasomarzi** [comment]
Thanks again for your help!
