### ISSUE TITLE
[BUG]  Memory-Mapped Storage fails to zero out missing tensors when reusing scratch dir path

### ISSUE THREAD

**Issue by kalyan0510** [pytorch/rl#2437]
## Describe the bug

When writing a tensor dict to memory-mapped storage, the expected behavior is for missing tensors to be replaced with tensors initialized to zero. However, when reusing a previously allocated memory-mapped storage path, missing tensors are not overwritten with zeros but instead retain stale data from previously saved tensor dictionaries. This leads to unexpected behavior when attempting to load tensor dictionaries with incomplete keys.

## To Reproduce
```python
import torch
from tensordict import TensorDict
from torchrl.data import LazyMemmapStorage

storage_path = '/tmp/new'
storage = LazyMemmapStorage(1000, scratch_dir=storage_path)
data1 = TensorDict({"a": torch.zeros(5, 3) + 1, "d": torch.zeros(5, 1) + 1}, [5])
storage.set(range(5), data1)
data2 = TensorDict({"a": torch.zeros(1, 3) + 2}, [1])
storage.set(range(5,6), data2)
print("Key 'd':", storage["d"])
# Output: Key 'd': MemoryMappedTensor([[1.], [1.], [1.], [1.], [1.], [0.]])

# rewrite with new data
storage = LazyMemmapStorage(1000, scratch_dir=storage_path)
data1 = TensorDict({"a": torch.zeros(1, 3) + 1, "d": torch.zeros(1, 1) + 1}, [1])
storage.set(range(1), data1)
data2 = TensorDict({"a": torch.zeros(5, 3) + 2}, [5])
storage.set(range(1,6), data2)
print("Key 'd':", storage["d"])
# Output: Key 'd': MemoryMappedTensor([[1.], [1.], [1.], [1.], [1.], [0.]])
# expected 'd': MemoryMappedTensor([[1.], [0.], [0.], [0.], [0.], [0.]])
```

This is probably a bad use of mapped storage. But in my case, I am using the replaybuffer with a mapped storage with scratch_dir set to a path 'on direct-attached storage' (just so it will be fast), but I was using the same path for different runs of same code.

When I run the code second time (with same path), I am seeing unexpected values.

## Expected behavior
I am not sure of the policy, whether it is expected that a tensor dict with missing key can be updated to a storage successfully. IMO It may be a good practice to force developer to provide full tensordict, or atleast make sure the storage rewrites values whenever a partial dict is updated. 

## System info

Describe the characteristic of your environment:
 * Describe how the library was installed (pip, source, ...)
 * Python version
 * Versions of any other relevant libraries

```python
import torchrl, numpy, sys
print(torchrl.__version__, numpy.__version__, sys.version, sys.platform)
0.5.0 1.24.4 3.8.19 | packaged by conda-forge | (default, Mar 20 2024, 12:47:35)
[GCC 12.3.0] linux

tensordict.__version__ = 0.5.0 (installed from nightly)
```

## Checklist

- [x ] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
I have cooked up a patch, I'll push it soon. It'll require upgrade both tensordict and torchrl but I'm about to make a release for both anyway!
