### ISSUE TITLE
[Feature Request] Support for Integrating Custom PettingZoo Environments with TorchRL's PettingZooEnv

### ISSUE THREAD

**Issue by andreamiele** [pytorch/rl#2461]
## Motivation

I’ve created a custom PettingZoo environment and I’m looking to integrate it with `benchmarl`, which is based on `torchrl`. Currently, the `PettingZooEnv` class is implemented in `torchrl`, but it's unclear what the process is for adding a new custom PettingZoo environment.

This feature request is motivated by the need for easier registration and compatibility of custom environments with `benchmarl` and `torchrl`. It could help streamline the process for users who develop their own PettingZoo environments.

## Solution

I would like to see a clear and concise method to register new PettingZoo environments, either through documentation or a straightforward integration pathway in `torchrl`. Ideally, this would allow custom PettingZoo environments to be added with minimal effort, leveraging the existing `PettingZooEnv` structure in `torchrl`.

## Alternatives

An alternative approach could be to manually modify the `PettingZooEnv` implementation, but this is less user-friendly and may require in-depth knowledge of both frameworks. A guide or tutorial for integrating custom environments would also be an alternative solution.

## Additional context

The current setup works well for predefined PettingZoo environments, but adding custom ones could be more intuitive. Enhancing the framework to support easier registration would save time and effort for users extending it with their own environments.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)

**Comment by matteobettini** [comment]
There is an example of adding a new pettingzoo env from scratch here https://github.com/facebookresearch/BenchMARL/pull/84

**Comment by matteobettini** [comment]
Essentially the process is jus:
- create an environment that inherits from `pettingzoo.ParallelEnv`
- then wrap it with
```python
 PettingZooWrapper(
            MyCustomEnv(),
            categorical_actions=True,
            device=device,
            seed=seed,
            return_state=False,
            **self.config,
        )
```

**Comment by andreamiele** [comment]
@matteobettini thanks for the link. The issue here is that i have a pettingzoo.AECEnv
would that work?
thanks!

**Comment by matteobettini** [comment]
Benchmarl is not comaptible with turn-based AECEnvs (https://github.com/facebookresearch/BenchMARL/issues/76)

But the torhrl wrapper is

**Comment by andreamiele** [comment]
Okay thanks for the information. 
I missed this point, i just thought i could put `parallel=False` in the PettingZooEnv.

Would you have any recommendation for AECEnv then @matteobettini ? Because I cannot make it parallel (the turn-based factor is important there).
Thanks again

**Comment by matteobettini** [comment]
You can put `parallel=False` in the PettingZooEnv. PettingZooWrapper wont even need you to set anything as it can already read it is not parallel.

You just can't use benchmarl as of now. You can use torchrl

**Comment by andreamiele** [comment]
Thanks a lot!
