### ISSUE TITLE
[BUG]flatten_tensordicts default to False

### ISSUE THREAD

**Issue by HGGshiwo** [pytorch/rl#2497]
## Describe the bug

# flatten_tensordicts default to False, while it is said should be True in the annotation.

## To Reproduce

Steps to reproduce the behavior.

Please try to provide a minimal example to reproduce the bug. Error messages and stack traces are also helpful.

Please use the markdown code blocks for both code and stack traces.

```python
import torchrl
```

```bash
Traceback (most recent call last):
  File ... 
```

## System info

Describe the characteristic of your environment:
 * Describe how the library was installed (pip, source, ...)
 * Python version
 * Versions of any other relevant libraries

```python
import torchrl, numpy, sys
print(torchrl.__version__, numpy.__version__, sys.version, sys.platform)
```

## Reason and Possible fixes

If you know or suspect the reason for this bug, paste the code lines and suggest modifications.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Hey can you provide a bit more details about this issue? What annotation are we talking about? Do you mean docstrings? Of which function?
Thanks!

**Comment by HGGshiwo** [comment]
> Hey can you provide a bit more details about this issue? What annotation are we talking about? Do you mean docstrings? Of which function? Thanks!

It is an arg in `Trainer.__init__`, the link is https://github.com/pytorch/rl/blob/main/torchrl/trainers/trainers.py#L639, you can see it is False in default, but True in comments

**Comment by vmoens** [comment]
Ah ok, trainer was not mentioned!
