### ISSUE TITLE
[BUG]Competitive MARL (DDPG) with TorchRL Tutorial - Memory map device other than CPU isn't supported

### ISSUE THREAD

**Issue by wangreit** [pytorch/rl#2515]
Hi! Thanks for sharing your work on MARL with VMAS! The tutorial was great and included lots of details and explanations! I have been looking for examples with non-sharing parameters between agents within the same group, as well as centralized vs decentralized training. This tutorial is exactly what I need! Thank you!

## Describe the bug

I was trying to test on the performance of the CPU version with PettingZoo vs GPU version with VMAS. Apparently on replay buffer section, I am getting the error "ValueError: Memory map device other than CPU isn't supported." so I follow the instruction to cast the data by adding a line of code "replay_buffer.append_transform(lambda x: x.to(device))". So my question is:

Would this step slows down the training since there is a transform to change the device from CPU to GPU?
Could we use a replay buffer other than storage=LazyMemmapStorage if there is such a limitation? Which one could we use?

Thanks!

## To Reproduce

Run the tutorial "Competitive Multi-Agent Reinforcement Learning (DDPG) with TorchRL Tutorial".  Use GPU and VMAS=True.

ValueError: Memory map device other than CPU isn't supported. To cast your data to the desired device, use `buffer.append_transform(lambda x: x.to(device)` or a similar transform.

## Possible fixes
replay_buffer.append_transform(lambda x: x.to(device))

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by matteobettini** [comment]
You are right! I think you can either:

- use another storage like LazyTensorStorage which can be on gpu
- append the transform like you suggest. This will be slower but it is needed if you need to keep the buffer on disk


I ll update the tutorial to illustrate this 

Cc @vmoens
