### ISSUE TITLE
[BUG] ImportError: cannot import name 'RayCollector' from partially initialized module 'torchrl.collectors.distributed.ray' (most likely due to a circular import) 

### ISSUE THREAD

**Issue by jianzhnie** [pytorch/rl#2524]
When attempting to import the RayCollector from the torchrl.collectors.distributed.ray module, an ImportError is raised due to a circular import issue. This error occurs during the initialization of the module, indicating a potential circular dependency within the codebase.

**Comment by albertbou92** [comment]
Hi! Could you please indicate which version are you using? I have no problem running

`from torchrl.collectors.distributed import RayCollector
`
with version 0.6.0

**Comment by albertbou92** [comment]
However, I just noticed something that could be the cause of your problem. Are you by any chance running the example in 

`https://github.com/pytorch/rl/blob/main/examples/distributed/collectors/multi_nodes/ray.py`

I believe the named of this file should be changes, as the name clashes with the ray library.
