### ISSUE TITLE
[BUG] `inferece_mode` decorator is preventing `state_dict` loading

### ISSUE THREAD

**Issue by GavinPHR** [pytorch/rl#529]
## Describe the bug

See title

## To Reproduce

Running example command `python sac.py` results in the following error:
```
Traceback (most recent call last):
  File "/Users/haoranpeng/Desktop/rl/examples/sac/sac.py", line 198, in main
    recorder_rm.load_state_dict(create_env_fn().state_dict())
  File "/Users/haoranpeng/Desktop/rl/torchrl/envs/transforms/transforms.py", line 418, in load_state_dict
    self.transform.load_state_dict(state_dict, **kwargs)
  File "/Users/haoranpeng/mambaforge/envs/torch_rl/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1667, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Compose:
        While copying the parameter named "transforms.2.loc", whose dimensions in the model are torch.Size([17]) and whose dimensions in the checkpoint are torch.Size([17]), an exception occurred : ('Inplace update to inference tensor outside InferenceMode is not allowed.
```

## Reason and Possible fixes

Remove `inference_mode` decorator from function `torchrl.trainers.helpers.envs.get_stats_random_rollout()`

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Thanks for reporting this, we'll fix it asap
