### ISSUE TITLE
PytorchRL contribution

### ISSUE THREAD

**Issue by giadefa** [pytorch/rl#547]
## Motivation

Over the years, we wrote the PytorchRL library:
https://github.com/PyTorchRL/pytorchrl
https://arxiv.org/abs/2007.02622

it seems to have several algorithms that pytorch/rl does not have.

## Solution

I encourage you to give it a look. The license is also MIT, so feel free to use the code if needed to be included here.
We will also check if we can reduce our codebase rebasing it on pytorch/rl.

**Comment by vmoens** [comment]
Hi @giadefa 
Thanks for pointing this repo! It's coverage looks quite extensive indeed. 
Just to make sure we're on the same line, our goal isn't to provide RL benchmarks and baselines but to give practitioners the building blocks they need to code up new stuff from scratch and swap components easily. Hence I'm not surprised that your repo covers more algos than ours.
We'd be more than happy to collaborate. Just let us know how we can help. If you'd like to use torchrl's primitives we can help you do that. Also if you feel that there are bits that you'd wish you had seen in the library but aren't there feel free to reach out to us.

**Comment by giadefa** [comment]
Hi Vincent,
same for PYTORCHRL. Our aim was to provide a modular and scalable (using
Ray) library for method experimentation and this is how we use it for our
own research.

The fact that we have many environments in PYTORCHRL and RL methods are
just a side effect of that while we try things out.

Maybe give a look at PYTORCHRL while we do the same for pytorch/rl and we
can maybe have a chat if there are interesting points to collaborate on.
The smaller the codebase of our code the better for us, so we might be
looking at different opportunities.

My email is ***@***.***

thanks,
Gianni.

**Comment by vmoens** [comment]
Closing this - unless you want to keep it open @giadefa
