### ISSUE TITLE
[BUG] SyncDataCollector resets all workers instead of one

### ISSUE THREAD

**Issue by jrobine** [pytorch/rl#570]
## Describe the bug

When using the SyncDataCollector with a ParallelEnv, **all** workers are reset if any of the workers is done.

## To Reproduce

```python
import torch
from torchrl.collectors import SyncDataCollector
from torchrl.envs import ParallelEnv
from torchrl.envs.libs.gym import GymEnv

if __name__ == '__main__':
    num_workers = 2
    num_steps = 4000

    create_env = lambda: GymEnv(env_name='PongNoFrameskip-v4', frame_skip=4)
    create_parallel_env = lambda: ParallelEnv(num_workers, create_env)

    collector = SyncDataCollector(create_parallel_env, frames_per_batch=num_workers, split_trajs=False)
    iterator = collector.iterator()
    episode_rewards = []
    cumulative_reward = torch.zeros(num_workers)
    for _ in range(num_steps):
        batch = next(iterator).squeeze(1)
        cumulative_reward += batch['reward'].squeeze(-1)
        done = batch['done'].squeeze(-1)
        episode_rewards.extend(cumulative_reward[done].tolist())
        cumulative_reward[done] = 0.
    collector.shutdown()
    print(episode_rewards)
```

This leads to the following episode rewards, although the lowest value for Pong should be -21:
```bash
[-21.0, -37.0, -41.0, -21.0]
```
The reason is that some episodes are reset without notice.

## Expected behavior

Only the workers which are actually done should be reset.

## Reason and Possible fixes

[In this line](https://github.com/pytorch/rl/blob/4862459866153a499a3c7e5d6df4238ffdc29fe8/torchrl/collectors/collectors.py#L588) the ParallelEnv is reset but `"reset_workers"` is ignored.  
A quick fix would be to replace the line with:
```python
self._tensordict.update(self.env.reset(self._tensordict), inplace=True)
```
This leads to the following output for the above code and seems to be correct:
```bash
[-21.0, -21.0, -21.0, -21.0, -21.0, -20.0, -20.0, -21.0]
```
But maybe there is a better solution.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Good catch I wonder why we haven't spotted this earlier!
The solution seems legit.
You can make a PR out of it, otherwise I'll take care of it.

Thanks for the thorough description
