### ISSUE TITLE
[BUG] Argument for `PPOLoss.get_entropy_bonus()` should probably not be optional

### ISSUE THREAD

**Issue by GavinPHR** [pytorch/rl#575]
## Describe the bug

https://github.com/pytorch/rl/blob/86a1a139682edc8bc747f088423937db1773aa24/torchrl/objectives/costs/ppo.py#L88-L94

The code doesn't seem to be compatible with `None` argument, will throw `AttributeError`.

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
good point, do you want me to take care of it?

**Comment by GavinPHR** [comment]
> good point, do you want me to take care of it?

please do thanks
