### ISSUE TITLE
[Feature Request] Remove wild imports in the library

### ISSUE THREAD

**Issue by vmoens** [pytorch/rl#609]
## Motivation

We usually adopt the wild import practice in our `__init__.py`:
```python
from .sub import *
```

However this requires to write a `__all__` list of classes and functions we want to expose + it is not very readable (it's nice to get a sense of what a module does just by looking at `__init__.py`.

## Solution

We should refactor this and import all relevant objects explicitly in `__init__.py`.

**Comment by adityagandhamal** [comment]
I can work on this @vmoens!
I'll submit a PR once I've finished refactoring all of the `__init__.py` files.

Just to make sure, once we explicitly import all the required stuff we'd no more need the `__all__` lists right?

**Comment by vmoens** [comment]
Hey! Thanks for this but we already have a PR opened with a solution!

**Comment by adityagandhamal** [comment]
No problem!

**Comment by vmoens** [comment]
Closed by #642
