### ISSUE TITLE
[BUG] Tests failing due to retiring of torch.testing.assert_allclose

### ISSUE THREAD

**Issue by sosmond** [pytorch/rl#643]
## Describe the bug

Due to [this change](https://github.com/pytorch/pytorch/pull/87974), `torch.testing.assert_allclose` has been removed which is causing unit tests to fail.

[Output from a recent CI run](https://app.circleci.com/pipelines/github/pytorch/rl/4214/workflows/9f006a20-055f-4a7a-83ea-d9d8b3fbc65c/jobs/98683)
```bash
FAILED test/test_rb.py::test_prototype_prb[device0-True-pk] - AttributeError: module 'torch.testing' has no attribute 'assert_allclose'
FAILED test/test_rb.py::test_prototype_prb[device0-True-td_error] - AttributeError: module 'torch.testing' has no attribute 'assert_allclose'
FAILED test/test_rb.py::test_prototype_prb[device0-False-pk] - AttributeError: module 'torch.testing' has no attribute 'assert_allclose'
FAILED test/test_rb.py::test_prototype_prb[device0-False-td_error] - AttributeError: module 'torch.testing' has no attribute 'assert_allclose'
```

## To Reproduce

Run `pytest` with pytorch nightly build installed. 

## Reason and Possible fixes

`torch.testing.assert_close` should be a drop-in replacement; [reference](https://github.com/pytorch/pytorch/issues/61844)

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Solved as of #644
