### ISSUE TITLE
[Feature Request] implement a `standard_normal` keyword arg for RewardScaling transform

### ISSUE THREAD

**Issue by vmoens** [pytorch/rl#646]
## Motivation

ObservationNorm transform can be called with standard normal (`(x-loc)/scale`) or regular (`x*scale+loc`). For consistency, we should implement this option for both.

I would keep it `False` by default for now (or default it to true and rename the transform to `RewardNorm`).

**Comment by vmoens** [comment]
Cc @adityagandhamal

**Comment by adityagandhamal** [comment]
> I would keep it `False` by default for now (or default it to true and rename the transform to `RewardNorm`).

As far as the consistency is concerned, I believe it should be kept `False` by default; as is wrt the ObservationNorm.

**Comment by adityagandhamal** [comment]
Should I change [this](https://github.com/pytorch/rl/blob/main/torchrl/envs/transforms/transforms.py#L1436) line to `return reward * scale + loc` so as to maintain the same idiom across the code?
