### ISSUE TITLE
[BUG] TensorDict.__repr__() shows wrong key in fields info for nested TensorDict after renaming

### ISSUE THREAD

**Issue by raphajaner** [pytorch/rl#652]
## Describe the bug

While working on the fix for #640, I noticed there might be another minor issue with nested `TensorDicts` when I rename the keys of the nested TensorDict. When printing the TensorDict / calling `TensorDict.__repr__()`, the old key is printed in the fields info. However, when directly accessing the nested TensorDict, everything works fine and the particular TensorDict is only accessible by the correct, new key.

## To Reproduce

```python
from torchrl.data import TensorDict

td = TensorDict({
    '1': TensorDict({
        '11': 1,
        '12': 2
    }, []),
    '2': 1,
}, [])

print(td)
print('\n')

td['1'].rename_key('11', 'CHANGED_KEY', True)
print('Key 11 has been renamed to \'CHANGED_KEY\'\n')

print(td)
print('\n')

print(td['1'])
print('\n')

print(td['1']['CHANGED_KEY')

```

## Expected behavior

Calling `TensorDict.__repr__()` should show the correct fields info after renaming a sub TensorDict.
## Screenshots
![image](https://user-images.githubusercontent.com/28293018/200349182-971534de-4590-4aee-8ddd-08a0160ec8e0.png)

## System info

Describe the characteristic of your environment:
 * Installed in develop mode
 * Python version: 3.8.10
 * Numpy version: 1.23.2
 * Distro: Ubuntu 20.04.5 LTS

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Thanks for reporting this!
FYI: We'll work on solving that in [the tensordict repo](https://github.com/pytorch-labs/), as we intend on deprecating the internal copy of the module.

**Comment by vmoens** [comment]
Closed as of https://github.com/pytorch-labs/tensordict/pull/30
