### ISSUE TITLE
No matching distribution found for torchrl

### ISSUE THREAD

**Issue by thomashirtz** [pytorch/rl#736]
## Describe the bug

Unable to install torchrl on a fresh venv that uses the latest torch and cuda with python 3.8

```
ERROR: Could not find a version that satisfies the requirement torchrl (from versions: none)
ERROR: No matching distribution found for torchrl
```

## To Reproduce

Created a fresh venv using Python 3.8 (I used Pycharm)
I ran `pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu117` on the terminal.

At this point pytorch works perfectly and with cuda.

I then ran `pip3 install torchrl` and got the error aforementioned.

## Expected behavior

TorchRL should install without errors

## System info

When I ran python on my venv:
```
Python 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
```

My OS:
```
Windows 10 Professionnel 22H2
```

NVIDIA RTX 2060 Max-Q
Driver 512.78

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Hi @thomashirtz 
From the looks of it, I think it's because we don't have published wheels for windows. 
Bear with me while we do that.
ETA one week, as we need to set up the tests and publication of the wheels + nightly.
In the meantime, you could have a go at building the lib from git 
```
pip install git+https://github.com/pytorch/rl.git
```
Or clone the repo and install it locally.
Let me know how it goes, happy to help further if anything breaks.

**Comment by thomashirtz** [comment]
Ok ! Thank you for your prompt response
I just checked and it worked

**Comment by matteobettini** [comment]
I have the same problem on Mac OS

Just created a fresh env with python 3.9 
and when i try `pip3 install torchrl` i get:

```
ERROR: Could not find a version that satisfies the requirement torchrl==0.0.3 (from versions: none)
ERROR: No matching distribution found for torchrl==0.0.3

```

**Comment by vmoens** [comment]
> I have the same problem on Mac OS
> 
> Just created a fresh env with python 3.9 and when i try `pip3 install torchrl` i get:
> 
> ```
> ERROR: Could not find a version that satisfies the requirement torchrl (from versions: none)
> ERROR: No matching distribution found for torchrl
> ```
> 
> MacOS 13.1 with M1 chip

We don't have wheels for M1 but you can simply do `pip install git+https://github.com/pytorch/rl` and it should work

**Comment by matteobettini** [comment]
The latest master crashes with
```
import torchrl

ImportError: cannot import name 'ProbabilisticTensorDictSequential' from 'tensordict.nn' (/opt/homebrew/Caskroom/miniforge/base/envs/torchrl/lib/python3.9/site-packages/tensordict/nn/__init__.py)
```

but 
```
git clone https://github.com/pytorch/rl
git checkout 0.0.3
```
works

**Comment by vmoens** [comment]
You're right, we need to update the tensordict wheels

```
pip install git+https://github.com/pytorch-labs/tensordict
```

**Comment by vmoens** [comment]
We'll be uploading the windows binaries soon

**Comment by jjgriffin2** [comment]
Please note that MacOS is not windows.

**Comment by matteobettini** [comment]
On. Mac OS the nightly still has this issue
```
(test) $ pip install torchrl-nightly
ERROR: Could not find a version that satisfies the requirement torchrl-nightly (from versions: none)
ERROR: No matching distribution found for torchrl-nightly
```

**Comment by vmoens** [comment]
There's a blocker for M1 which is that we don't have access to M1 nodes on pytorch-labs so tensordict cannot produce nightlies or even binaries in general.
One solution would be to do it via torchrl (a bit of a hack but we did it in the past). If anyone wants to give it a shot I'd be happy to support.

The idea would be to copy the pipelines to create binaries in tensordict within torchrl and do a custom GHA workflow that would checkout tensordict and not torchrl, and upload the binaries where appropriate.

Anyone's up for it?
