### ISSUE TITLE
[Feature Request] Remove the Nd*TensorSpec classes

### ISSUE THREAD

**Issue by vmoens** [pytorch/rl#771]
## Motivation

The usage of the non-Nd TensorSpec classes is limited, as they are essentially special cases of the Nd specs. 
To simplify things and for better maintenance we should get rid of the non Nd specs and rename the Nd to their counterpart names, ie

Remove
```
BoundedTensorSpec, UnboundedContinuousTensorSpec, UnboundedDiscreteTensorSpec
```
And rename 
```
NdBoundedTensorSpec, NdUnboundedContinuousTensorSpec, NdUnboundedDiscreteTensorSpec
```
With these names

**Comment by riiswa** [comment]
I'm on it 😄
