### ISSUE TITLE
[BUG] Stacked tensordicts with nested keys crash `env.step()`

### ISSUE THREAD

**Issue by matteobettini** [pytorch/rl#784]
## Describe the bug

Due to multiagent applications my env needs to return `tensordict_out = torch.stack(agent_tds,dim=0)` from `env._step()`  with nested keys. 
This creates a `LazyStackedTensorDict`.

The subsequent logic of `env.step()` performs certain operations on the `tensordict_out`which crash if the latter has nested keys.

This can be solved by calling `to_tensordict()` before the end of the `_step()` but this is possible only when the stack is homogenous and not wheen it is heterogenous as in #766.

## To Reproduce

Create `LazyStackedTensorDict` and return it in the `_step` implementation

```bash
test/test_libs.py:525 (TestVmas.test_vmas_seeding[flocking])
Traceback (most recent call last):
  File "/Users/Matteo/PycharmProjects/torchrl/test/test_libs.py", line 537, in test_vmas_seeding
    tdrollout.append(env.rollout(max_steps=10))
  File "/Users/Matteo/PycharmProjects/torchrl/torchrl/envs/common.py", line 605, in rollout
    tensordict = self.step(tensordict)
  File "/Users/Matteo/PycharmProjects/torchrl/torchrl/envs/common.py", line 343, in step
    tensordict_out_select = tensordict_out.select(*obs_keys)
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4325, in select
    raise TypeError(
TypeError: All keys passed to LazyStackedTensorDict.select must be strings. Found ('info', 'velocity_rew') of type <class 'tuple'>. Note that LazyStackedTensorDict does not yet support nested keys.
```

**Comment by matteobettini** [comment]
There is another related craswh of heterogenous stacks in the `EnvBase.step()` function:

```bash
Traceback (most recent call last):
  File "/Users/Matteo/PycharmProjects/torchrl/test/test_libs.py", line 537, in test_vmas_seeding
    tdrollout.append(env.rollout(max_steps=10))
  File "/Users/Matteo/PycharmProjects/torchrl/torchrl/envs/common.py", line 605, in rollout
    tensordict = self.step(tensordict)
  File "/Users/Matteo/PycharmProjects/torchrl/torchrl/envs/common.py", line 345, in step
    tensordict_out.set("next", tensordict_out_select)
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4096, in set
    proc_tensor = tensor.unbind(self.stack_dim)
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 1214, in unbind
    return tuple(
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 1215, in <genexpr>
    self.apply(
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 628, in apply
    for key, item in self.items():
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 832, in items
    yield k, self.get(k)
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4191, in get
    raise RuntimeError(
RuntimeError: Found more than one unique shape in the tensors to be stacked ({torch.Size([4, 4]), torch.Size([4, 8])}). This is likely due to a modification of one of the stacked TensorDicts, where a key has been updated/created with an uncompatible shape. If the entries are intended to have a different shape, use the get_nestedtensor method instead.

```

**Comment by vmoens** [comment]
Interesting, I [think](https://github.com/pytorch-labs/tensordict/pull/140) this should solve it

**Comment by matteobettini** [comment]
Thanks ,I'll try it out when it s done!

**Comment by matteobettini** [comment]
On it! Ty

**Comment by matteobettini** [comment]
Perfect! The first issue is fixed and the second issue in step is fixed.

Hwoever with rollout we still have one issue

```
Traceback (most recent call last):
  File "/Users/Matteo/PycharmProjects/torchrl/test/test_libs.py", line 537, in test_vmas_seeding
    tdrollout.append(env.rollout(max_steps=10))
  File "/Users/Matteo/PycharmProjects/torchrl/torchrl/envs/common.py", line 612, in rollout
    tensordict = step_mdp(
  File "/Users/Matteo/PycharmProjects/torchrl/torchrl/envs/utils.py", line 88, in step_mdp
    select_tensordict = select_tensordict.update(tensordict.get("next"))
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4542, in update
    for key, value in input_dict_or_td.items():
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 837, in items
    yield k, self.get(k)
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4212, in get
    raise RuntimeError(
RuntimeError: Found more than one unique shape in the tensors to be stacked ({torch.Size([4, 4]), torch.Size([4, 8])}). This is likely due to a modification of one of the stacked TensorDicts, where a key has been updated/created with an uncompatible shape. If the entries are intended to have a different shape, use the get_nestedtensor method instead.
```

**Comment by vmoens** [comment]
This is probably due to the fact that when updating a lazy stack with another lazy stack we call get for the second, while we could simply update the sub-tensordicts
I'll do a PR with that

**Comment by vmoens** [comment]
https://github.com/pytorch-labs/tensordict/pull/142

**Comment by matteobettini** [comment]
seem to work but `rollout` by default has `return_conituous=True` which causes this error
```
Traceback (most recent call last):
  File "/Users/Matteo/PycharmProjects/torchrl/test/test_libs.py", line 537, in test_vmas_seeding
    tdrollout.append(env.rollout(max_steps=10))
  File "/Users/Matteo/PycharmProjects/torchrl/torchrl/envs/common.py", line 626, in rollout
    return out_td.contiguous()
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4269, in contiguous
    source = {key: value.contiguous() for key, value in self.items()}
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4269, in <dictcomp>
    source = {key: value.contiguous() for key, value in self.items()}
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4269, in contiguous
    source = {key: value.contiguous() for key, value in self.items()}
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4269, in <dictcomp>
    source = {key: value.contiguous() for key, value in self.items()}
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 837, in items
    yield k, self.get(k)
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4206, in get
    tensors = [td.get(key, default=default) for td in self.tensordicts]
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4206, in <listcomp>
    tensors = [td.get(key, default=default) for td in self.tensordicts]
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4212, in get
    raise RuntimeError(
RuntimeError: Found more than one unique shape in the tensors to be stacked ({torch.Size([4, 4]), torch.Size([4, 8])}). This is likely due to a modification of one of the stacked TensorDicts, where a key has been updated/created with an uncompatible shape. If the entries are intended to have a different shape, use the get_nestedtensor method instead.
```

as expected.

Should we leave like this? Because functions such as `check_env()` in the tests use the defaults for rollouts

**Comment by matteobettini** [comment]
Also, when trying to use `ParallelEnv`with these heterogenous tds we get 

```bash
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/envs/torchrl/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/opt/homebrew/Caskroom/miniforge/base/envs/torchrl/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/Matteo/PycharmProjects/torchrl/torchrl/envs/vec_env.py", line 1033, in _run_worker_pipe_shared_mem
    tensordict.update_(_td.select(*step_keys, strict=False))
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 721, in update_
    for key, value in input_dict_or_td.items():
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 837, in items
    yield k, self.get(k)
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4212, in get
    raise RuntimeError(
RuntimeError: Found more than one unique shape in the tensors to be stacked ({torch.Size([32, 4]), torch.Size([32, 8])}). This is likely due to a modification of one of the stacked TensorDicts, where a key has been updated/created with an uncompatible shape. If the entries are intended to have a different shape, use the get_nestedtensor method instead.
```

**Comment by vmoens** [comment]
> seems to work but `rollout` by default has `return_conitguous=True` which causes this error
> 
> ```
> Traceback (most recent call last):
>   File "/Users/Matteo/PycharmProjects/torchrl/test/test_libs.py", line 537, in test_vmas_seeding
>     tdrollout.append(env.rollout(max_steps=10))
>   File "/Users/Matteo/PycharmProjects/torchrl/torchrl/envs/common.py", line 626, in rollout
>     return out_td.contiguous()
>   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4269, in contiguous
>     source = {key: value.contiguous() for key, value in self.items()}
>   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4269, in <dictcomp>
>     source = {key: value.contiguous() for key, value in self.items()}
>   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4269, in contiguous
>     source = {key: value.contiguous() for key, value in self.items()}
>   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4269, in <dictcomp>
>     source = {key: value.contiguous() for key, value in self.items()}
>   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 837, in items
>     yield k, self.get(k)
>   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4206, in get
>     tensors = [td.get(key, default=default) for td in self.tensordicts]
>   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4206, in <listcomp>
>     tensors = [td.get(key, default=default) for td in self.tensordicts]
>   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4212, in get
>     raise RuntimeError(
> RuntimeError: Found more than one unique shape in the tensors to be stacked ({torch.Size([4, 4]), torch.Size([4, 8])}). This is likely due to a modification of one of the stacked TensorDicts, where a key has been updated/created with an uncompatible shape. If the entries are intended to have a different shape, use the get_nestedtensor method instead.
> ```
> 
> as expected.
> 
> Should we leave like this? Because functions such as `check_env()` in the tests use the defaults for rollouts

I think in that case we need to document that for the specific use case where you want LazyStacked output, you should disable that. One way to do this is to capture the error and rewrite something more explicit. Wdyt?

**Comment by vmoens** [comment]
> Also, when trying to use `ParallelEnv`with these heterogenous tds we get
> 
> ```shell
> Traceback (most recent call last):
>   File "/opt/homebrew/Caskroom/miniforge/base/envs/torchrl/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/opt/homebrew/Caskroom/miniforge/base/envs/torchrl/lib/python3.9/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/Users/Matteo/PycharmProjects/torchrl/torchrl/envs/vec_env.py", line 1033, in _run_worker_pipe_shared_mem
>     tensordict.update_(_td.select(*step_keys, strict=False))
>   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 721, in update_
>     for key, value in input_dict_or_td.items():
>   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 837, in items
>     yield k, self.get(k)
>   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4212, in get
>     raise RuntimeError(
> RuntimeError: Found more than one unique shape in the tensors to be stacked ({torch.Size([32, 4]), torch.Size([32, 8])}). This is likely due to a modification of one of the stacked TensorDicts, where a key has been updated/created with an uncompatible shape. If the entries are intended to have a different shape, use the get_nestedtensor method instead.
> ```

Yeah I was thinking that this would happen eventually.
Basically ParallelEnv and the collectors build (or try to build) contiguous tensordicts. 
For parallelEnv, we can probably use something like `ParallelEnv(..., share_individual_td=True)` (which is False by default).
This creates a single TensorDict for every sub-process (rather than one contiguous tensordict accessed by all processes at a given index). There should be a similar solution for your problem (I doubt that this will work out of the box, but may be worth a try!)

Can you share the code snippet that gives this error, I can give a shot at debugging it.

**Comment by matteobettini** [comment]
> > seems to work but `rollout` by default has `return_conitguous=True` which causes this error
> > ```
> > Traceback (most recent call last):
> >   File "/Users/Matteo/PycharmProjects/torchrl/test/test_libs.py", line 537, in test_vmas_seeding
> >     tdrollout.append(env.rollout(max_steps=10))
> >   File "/Users/Matteo/PycharmProjects/torchrl/torchrl/envs/common.py", line 626, in rollout
> >     return out_td.contiguous()
> >   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4269, in contiguous
> >     source = {key: value.contiguous() for key, value in self.items()}
> >   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4269, in <dictcomp>
> >     source = {key: value.contiguous() for key, value in self.items()}
> >   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4269, in contiguous
> >     source = {key: value.contiguous() for key, value in self.items()}
> >   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4269, in <dictcomp>
> >     source = {key: value.contiguous() for key, value in self.items()}
> >   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 837, in items
> >     yield k, self.get(k)
> >   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4206, in get
> >     tensors = [td.get(key, default=default) for td in self.tensordicts]
> >   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4206, in <listcomp>
> >     tensors = [td.get(key, default=default) for td in self.tensordicts]
> >   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4212, in get
> >     raise RuntimeError(
> > RuntimeError: Found more than one unique shape in the tensors to be stacked ({torch.Size([4, 4]), torch.Size([4, 8])}). This is likely due to a modification of one of the stacked TensorDicts, where a key has been updated/created with an uncompatible shape. If the entries are intended to have a different shape, use the get_nestedtensor method instead.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > as expected.
> > Should we leave like this? Because functions such as `check_env()` in the tests use the defaults for rollouts
> 
> I think in that case we need to document that for the specific use case where you want LazyStacked output, you should disable that. One way to do this is to capture the error and rewrite something more explicit. Wdyt?

yes that sounds good

**Comment by matteobettini** [comment]
> > Also, when trying to use `ParallelEnv`with these heterogenous tds we get
> > ```shell
> > Traceback (most recent call last):
> >   File "/opt/homebrew/Caskroom/miniforge/base/envs/torchrl/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
> >     self.run()
> >   File "/opt/homebrew/Caskroom/miniforge/base/envs/torchrl/lib/python3.9/multiprocessing/process.py", line 108, in run
> >     self._target(*self._args, **self._kwargs)
> >   File "/Users/Matteo/PycharmProjects/torchrl/torchrl/envs/vec_env.py", line 1033, in _run_worker_pipe_shared_mem
> >     tensordict.update_(_td.select(*step_keys, strict=False))
> >   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 721, in update_
> >     for key, value in input_dict_or_td.items():
> >   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 837, in items
> >     yield k, self.get(k)
> >   File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4212, in get
> >     raise RuntimeError(
> > RuntimeError: Found more than one unique shape in the tensors to be stacked ({torch.Size([32, 4]), torch.Size([32, 8])}). This is likely due to a modification of one of the stacked TensorDicts, where a key has been updated/created with an uncompatible shape. If the entries are intended to have a different shape, use the get_nestedtensor method instead.
> > ```
> 
> Yeah I was thinking that this would happen eventually. Basically ParallelEnv and the collectors build (or try to build) contiguous tensordicts. For parallelEnv, we can probably use something like `ParallelEnv(..., share_individual_td=True)` (which is False by default). This creates a single TensorDict for every sub-process (rather than one contiguous tensordict accessed by all processes at a given index). There should be a similar solution for your problem (I doubt that this will work out of the box, but may be worth a try!)
> 
> Can you share the code snippet that gives this error, I can give a shot at debugging it.

The code snippet I am using is the main with #785 and #788 merged, tohave vmas and allow it to work.

then you just need to run
```    
env = ParallelEnv(10, lambda: VmasEnv("simple_crypto", num_envs=32))
print(env.rollout(max_steps=10))
```

**Comment by vmoens** [comment]
@matteobettini I had a look into this
I think the main problem is that the spec and the result of the rollout don't match (one is a contiguous tensor, the other is a stacked tensor with diverging shapes)
To create the buffers in ParallelEnv, we generate fake data from the spec. Since they don't match you get this error.
I can create the StackedCompositeSpec we talked about previously if you wish, which will hopefully work somewhat like a tuple box.

**Comment by vmoens** [comment]
Follow-up on this
It's a bit more complex than I thought
Qq: 
1. Do we want to allow CompositeSpecs with different keys? With LazyStackedTensorDict you can do that, but I'm not sure it's something we need right now. Maybe we can leave this for future development, and tell the users that want to do that that this is not supported yet?
2. TensorDict can be indexed along the keys or along the dims. Do we want the same thing here, ie
```python
stacked_spec = StackedCompositeSpec(
   CompositeSpec(action=action_spec1),
   CompositeSpec(action=action_spec2),
)
stacked_spec[0] # returns first spec
stacked_spec[range(2)] # returns an object identical to this one

stacked_spec["action"]  # what should we return here?
```
3. What should we do in the last case where one tries to get the "action" key? Stacking specs that are not composite is hard bc we can't return a LazyStackedTensorDict (since we don't have keys). We could create a `StackedSpec` class that would not allow you to use `rand` `zero` or `is_in`, but that's a bit useless. Or a `StackedSpec` class that works with tuples?

Do you have suggestions about what this API should look like?

**Comment by matteobettini** [comment]
> 1. Do we want to allow CompositeSpecs with different keys?

I do not need this feature right now. I can imagine cases when this can come useful. For example imagine having agents wich have different sensors (one has a lidar and one a camera). In this case the observation is a Composite spec with the keys lidar and camera and each agent has only one of the two. A workaround to this is setting the dim for the observation that the agent does not have to 0. 

EG
```python
td["observation“]["lidar"].shape = (2, 10, 32, *)

td["observation“]["lidar"][0].shape = (10, 32, 15) # agent 0 has lidar
td["observation“]["lidar"][1].shape = (10, 32, 0) # agent 1 has no lidar
```

This is not clean but does the job. In the future implementing 1. would be useful to avoid stuff like this.

> 2. TensorDict can be indexed along the keys or along the dims.

Currently what happens is

```python
input_spec = CompositeSpec(
      action=(
          UnboundedContinuousTensorSpec(
              shape=torch.Size((1,)),
              device="cpu",
          )
      )
  )
print(input_spec["action"])
UnboundedContinuousTensorSpec(
     shape=torch.Size([1]), space=ContinuousBox(minimum=-inf, maximum=inf), device=cpu, dtype=torch.float32, domain=continuous)
```

What I would do with the StackedCompositeSpec is

```python
input_spec = StackedCompositeSpec(
   CompositeSpec(action=UnboundedContinuousTensorSpec(shape=torch.Size((1,3,2))),
   CompositeSpec(action=UnboundedContinuousTensorSpec(shape=torch.Size((1,5,2))),
)
print(input_spec["action"])
StackedUnboundedContinuousTensorSpec(
     shape=torch.Size([1, *, 2]), space=ContinuousBox(minimum=-inf, maximum=inf), device=cpu, dtype=torch.float32, domain=continuous)
```

> 3. What should we do in the last case where one tries to get the "action" key?

if the above is difficult because we cannot create the `StackedSpec` class, maybe we can return a tuple

```python
ì
print(input_spec["action"])
[
UnboundedContinuousTensorSpec(
     shape=torch.Size([1,3,2]), space=ContinuousBox(minimum=-inf, maximum=inf), device=cpu, dtype=torch.float32, domain=continuous),
UnboundedContinuousTensorSpec(
     shape=torch.Size([1,5,2]), space=ContinuousBox(minimum=-inf, maximum=inf), device=cpu, dtype=torch.float32, domain=continuous)
]
```

**Comment by matteobettini** [comment]
I hadn't checked but there is still one error in `__repr__` when rolling out an env with heterogenous lazy stacks:

```python
   env = VmasEnv("simple_crypto", num_envs=32).rollout(10, return_contiguous=False)
```

```bash
Traceback (most recent call last):
  File "/Users/Matteo/PycharmProjects/VectorizedMultiAgentSimulator/vmas/examples/torch_rl.py", line 59, in <module>
    print(env.rollout(10, return_contiguous=False))
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 1725, in __repr__
    fields = _td_fields(self)
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 5699, in _td_fields
    sorted([_make_repr(key, item, td) for key, item in td.items_meta()])
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 5699, in <listcomp>
    sorted([_make_repr(key, item, td) for key, item in td.items_meta()])
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 5691, in _make_repr
    return f"{key}: {repr(tensordict.get(key))}"
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 1725, in __repr__
    fields = _td_fields(self)
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 5699, in _td_fields
    sorted([_make_repr(key, item, td) for key, item in td.items_meta()])
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 5699, in <listcomp>
    sorted([_make_repr(key, item, td) for key, item in td.items_meta()])
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 859, in items_meta
    yield k, self._get_meta(k)
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 570, in _get_meta
    return self._dict_meta[key]
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/utils.py", line 267, in __missing__
    value = self.fun(key)
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/tensordict.py", line 4261, in _make_meta
    return torch.stack(
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/metatensor.py", line 327, in __torch_function__
    return META_HANDLED_FUNCTIONS[func](*args, **kwargs)
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/metatensor.py", line 496, in stack_meta
    return _stack_meta(
  File "/Users/Matteo/PycharmProjects/tensordict/tensordict/metatensor.py", line 464, in _stack_meta
    shape = list(shape)
TypeError: 'NoneType' object is not iterable
```

**Comment by vmoens** [comment]
Seems like a tensordict issue, do you mind opening the issue there too?

**Comment by matteobettini** [comment]
Yep, np I'll also look a bit more into it to see if i can find a quick fix
