### ISSUE TITLE
[Feature Request] Refactor the `max_frames_per_traj` from the collector to using the related transform

### ISSUE THREAD

**Issue by vmoens** [pytorch/rl#813]
## Motivation

As pointed in #807 there are 2 ways of setting a max number of frames for a transform in a collector: using the `max_frames_per_traj` keyword or the [`StepCounter`](https://github.com/pytorch/rl/blob/d4d45ecf2969a879a3ad942aa812ab3b17ad0d31/torchrl/envs/transforms/transforms.py#LL2598C7-L2598C18) transform.

Since the latter is designed on purpose for this, it would make sense to deprecate the keyword of the collector.

- [ ] Replace the behaviour of `max_frames_per_traj` with the transform, adapt the tests, raise a warning if `max_frames_per_traj` is non negative
- [ ] Deprecate `max_frames_per_traj`

**Comment by vmoens** [comment]
cc @matteobettini @riiswa

**Comment by riiswa** [comment]
I will work on it :)

**Comment by vmoens** [comment]
Awesome
It would make sense to address the corresponding item [here](https://github.com/pytorch/rl/issues/806) before, I guess
