### ISSUE TITLE
[Feature Request] multi-agent tutorial

### ISSUE THREAD

**Issue by RiqiangGao** [pytorch/rl#862]
## Motivation

Multi-agent RL is a hot topic, while tutorials are lacked here. 

## Solution

Could you please add a tutorial for multi-agent RL? Thanks

**Comment by vmoens** [comment]
Thanks @RiqiangGao 
Will do ASAP! It's an active area of development in the lib, we definitely should work on the doc

cc @matteobettini (not that you need to do it, just FYI)

**Comment by RiqiangGao** [comment]
Just a FYI, some MARL packages like https://github.com/Farama-Foundation/PettingZoo seem very good, it would be great if they can be integrated into torchrl.

**Comment by matteobettini** [comment]
I would be happy to help you in making it.

I was mainly waiting to reshape a few library features (such as multi-agent collectors #828) and other stuff that might not be super smooth yet in multi-agent torchrl. (I still haven't looked at how losses and trainers behave in multi-agent settings here).

**Comment by matteobettini** [comment]
> e MARL packages like https://github.com/Farama-Foundation/PettingZoo seem very good, it would be great if they can be integrated into torchrl.

Wrapping PettingZoo would be cool and useful. I know that they are in the stage of making breaking changes to the API though https://github.com/Farama-Foundation/PettingZoo/issues/803

**Comment by matteobettini** [comment]
#1027 Shows some examples of multiagent training in [VMAS](https://github.com/proroklab/VectorizedMultiAgentSimulator)

**Comment by pseudo-rnd-thoughts** [comment]
> Wrapping PettingZoo would be cool and useful. I know that they are in the stage of making breaking changes to the API though [Farama-Foundation/PettingZoo#803](https://github.com/Farama-Foundation/PettingZoo/issues/803)

Hey, I just saw this. That PR was purely an experimental idea and we haven't made any change nor have any ideas to PZ currently. 
There already exist several tutorials for PettingZoo (https://pettingzoo.farama.org/tutorials/cleanrl/implementing_PPO/) for any tutorial to build upon

**Comment by matteobettini** [comment]
We have a multi-agent tutorial online, check it out at https://pytorch.org/rl/tutorials/multiagent_ppo.html
