### ISSUE TITLE
[BUG] EGreedyWrapper seems to break collector

### ISSUE THREAD

**Issue by smorad** [pytorch/rl#865]
## Describe the bug

Wrapping policies in `EGreedyWrapper` appears to break the collector

## To Reproduce

```python
from torchrl.envs.libs.gym import GymEnv
from torchrl.collectors import SyncDataCollector
from tensordict.nn import TensorDictSequential, TensorDictModule
from torchrl.modules import QValueActor, EGreedyWrapper
from torch import nn


env = GymEnv("Pendulum-v1", from_pixels=False)
env_make = lambda: GymEnv("Pendulum-v1", from_pixels=False)
module_a = TensorDictModule(nn.LazyLinear(32), in_keys=["observation"], out_keys=["hidden"])
module_b = QValueActor(nn.Linear(32, 2), in_keys=["hidden"])
policy = TensorDictSequential(module_a, module_b)
greedy_policy = EGreedyWrapper(policy, spec=env.action_spec)

collector = SyncDataCollector(
    env_make,
    total_frames=100,
    policy=policy
)

greedy_collector = SyncDataCollector(
    env_make,
    total_frames=100,
    policy=greedy_policy
)

# This works
for data in collector:
    break

# This fails
for data in greedy_collector:
    break
```

```
Traceback (most recent call last):
  File "/Users/smorad/code/rl/examples/rdqn/test.py", line 21, in <module>
    greedy_collector = SyncDataCollector(
  File "/Users/smorad/miniforge3/envs/torch_rl/lib/python3.9/site-packages/torchrl/collectors/collectors.py", line 438, in __init__
    and all(v is not None for v in self.policy.spec.values())
AttributeError: 'BoundedTensorSpec' object has no attribute 'values'
```

## Expected behavior

No crashing
## System info
Library built from source at 20b6fc92574959b5edd0a7658e3d45ecadaef2eb

```
None 1.22.1 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:01:00)
[Clang 13.0.1 ] darwin
```

## Reason and Possible fixes

If you know or suspect the reason for this bug, paste the code lines and suggest modifications.

## Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by smorad** [comment]
The issue was wrapping the full policy (instead of just the `QValueActor`) in the wrapper. The error message was quite confusing, making it seem like the error was in the collector or env. Perhaps some assert in the `EGreedyWrapper` could produce a more informative backtrace.


For posterity, the following works:

```python
from torchrl.envs.libs.gym import GymEnv
from torchrl.collectors import SyncDataCollector
from tensordict.nn import TensorDictSequential, TensorDictModule
from torchrl.modules import QValueActor, EGreedyWrapper
from torch import nn


env = GymEnv("Pendulum-v1", from_pixels=False)
env_make = lambda: GymEnv("Pendulum-v1", from_pixels=False)
module_a = TensorDictModule(nn.LazyLinear(32), in_keys=["observation"], out_keys=["hidden"])
module_b = QValueActor(nn.Linear(32, 2), in_keys=["hidden"])
policy = TensorDictSequential(module_a, module_b)
greedy_policy = TensorDictSequential(
    module_a, EGreedyWrapper(module_b, spec=env.action_spec)
)

collector = SyncDataCollector(
    env_make,
    total_frames=100,
    policy=policy
)

greedy_collector = SyncDataCollector(
    env_make,
    total_frames=100,
    policy=greedy_policy
)

# This works
for data in collector:
    break

# This fails
for data in greedy_collector:
    break
```

**Comment by vmoens** [comment]
Thanks for reporting this! I'll provide a fix ASAP

**Comment by smorad** [comment]
One more question related to this: It seems like recurrent models cannot be wrapped by `QValueActor`, because `QValueActor` overrides `TensorDictModel.out_keys`, rather than appending to it. Recurrent models generally need to output their recurrent state via `out_keys`.

This becomes an issue once we start working with target networks. `DQNLoss` requires we pass the target value function which must be wrapped in `QValueActor`. We can pass a copy of `module_b` to `DQNLoss` as the target network, but`module_a` will still be shared between the target and learning network. I think in many cases we do not want to share `module_a` between the target and learning network.

**Comment by vmoens** [comment]
Yep I agree QValueActor should be more flexible.

**Comment by smorad** [comment]
Is there a reason all the loss functions take `TensorDictModules` instead of `TensorDict`? The latter seems like it could be more flexible (and functional) by separating the model bits from the loss computation bits.

**Comment by vmoens** [comment]
The philosophy is that we'd like to have loss modules that you can call with data collected from the buffer and get your loss value in one go.
That has its perks and disadvantages and, as much as we could, I'd wish we could write efficient functional. 

TorchRL's loss modules __do__ differ from torch.nn ones as they are stateful, but the thing is that in RL any algorithm-specific loss is convoluted and must be implemented with a substantial amount of control flow (calling the actor with gradient at `t` and without at `t+1` for SARSA-like, calling the actor without retrieving an action to get a probability distribution in PPO, etc). But again, any functional would be welcome!

**Comment by smorad** [comment]
Closing this as it is now possible to chain modules in a sequence, e.g. `policy = TensordictSequential(rnn_tdmodule, mlp_tdmodule, ..., qvalue_module)`, resolving this issue.
