### ISSUE TITLE
[BUG] AttributeError: 'TensorDict' object has no attribute '_get_meta' when using rollout on DMcontrol suite

### ISSUE THREAD

**Issue by atonkamanda** [pytorch/rl#884]
## Describe the bug

```python

from torchrl.envs.libs.dm_control import DMControlEnv

env = DMControlEnv("acrobot", "swingup",from_pixels=True)

def policy(tensordict):
    tensordict.set("action", env.action_spec.rand())
    return tensordict

tensordict = env.reset()
tensordict_rollout = env.rollout(max_steps=100, policy=policy)
env.close()
```
Check a non-existing attribute and gives me this error.

```bash
File "/Tmp/anaconda3/envs/acc/lib/python3.10/site-packages/torchrl/envs/common.py", line 339, in step
    if tensordict_out._get_meta("reward").dtype is not self.reward_spec.dtype:
AttributeError: 'TensorDict' object has no attribute '_get_meta'
```

Pretty sure the code used to work 1 week ago I've tried both the nightly and the stable version and still get this am I doing something wrong ? 

Thank you.

## Checklist

- [ ] I have checked that there is no similar issue in the repo (**required**)
- [ ] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [ ] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
We have deprecated the meta tensors from tensordict a couple of weeks ago. The nightly should fix this. What could happen is that the nightly and non-nightly conflict:
check that torchrl and torchrl-nightly do not appear in `pip list`. If they both do, remove the non-nightly, and upgrade the nightly. Hope that helps!

**Comment by vmoens** [comment]
Closing this as (I think) it's been completed but happy to reopen otherwise
