### ISSUE TITLE
Align Torch RL with Meta ReAgent Libraries

### ISSUE THREAD

**Issue by pprokevin** [pytorch/rl#891]
## Motivation

Meta has released ReAgent as generic RL library for production use,
including Multi Armed Bandit RL.

## Solution

TorchRL team should discuss with ReAgent Meta team (ie same company),
to align TorchRL API/modularity with ReAgent framework and then to Productionization.

Too many RL libraries are focused on Jupyter nobteook experimentation/ local resarch experiments,
what people needs is RL towards Productionizaton.
You can ask Meta ReAgent team to confirm this,

**Comment by vmoens** [comment]
Thanks @pprokevin 
This is something we are working on, as you can imagine :) 
We'll keep you posted on the progress.

**Comment by vmoens** [comment]
Thanks, we know about these libraries. They are indeed well curated and rightfully very popular.
Is there anything specific that you think is missing in torchrl? We won't just copy-paste the content of other libraries, if you see what I mean

**Comment by vmoens** [comment]
I don't really see any concrete advice or feedback here. What action should we take? What is missing? 
As I've said earlier we're not doing what ReAgent is doing, I believe our missions are complementary and diverse. We won't copy paste their code.

I'll be closing this issue, feel free to reopen if you have concrete action items that we can turn into new features, or open PRs with the changes you'd like to see.
