### ISSUE TITLE
[BUG] Cannot initialize the transform if parent env is not defined

### ISSUE THREAD

**Issue by anthony0727** [pytorch/rl#902]
## Describe the bug
 
running example throws `Cannot initialize the transform if parent env is not defined`

## To Reproduce

```python dreamer/dreamer.py```

```bash
(py39) {my machine}$ python examples/dreamer/dreamer.py env_name="walker" env_task="walk" env_library="dm_control"
EGL_DEVICE_ID:  1
sys:1: UserWarning: 
'config' is validated against ConfigStore schema with the same name.
This behavior is deprecated in Hydra 1.1 and will be removed in Hydra 1.2.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/automatic_schema_matching for migration instructions.
/home/anthony/.pyenv/versions/py39/lib/python3.9/site-packages/hydra/main.py:90: UserWarning: 
'config' is validated against ConfigStore schema with the same name.
This behavior is deprecated in Hydra 1.1 and will be removed in Hydra 1.2.
See https://hydra.cc/docs/1.2/upgrades/1.0_to_1.1/automatic_schema_matching for migration instructions.
  _run_hydra(
Using device cuda:0
Error executing job with overrides: ['env_name=walker', 'env_task=walk', 'env_library=dm_control']
Traceback (most recent call last):
  File "/home/anthony/rl/examples/dreamer/dreamer.py", line 111, in main
    initialize_observation_norm_transforms(
  File "/home/anthony/rl/torchrl/trainers/helpers/envs.py", line 485, in initialize_observation_norm_transforms
    transform.init_stats(num_iter=num_iter, key=key)
  File "/home/anthony/rl/torchrl/envs/transforms/transforms.py", line 1508, in init_stats
    raise RuntimeError(
RuntimeError: Cannot initialize the transform if parent env is not defined. 
```

## Expected behavior

example running

## System info

Describe the characteristic of your environment:
0.0.4 1.23.5 3.9.16 (main, Jan 17 2023, 03:16:52) 
[GCC 9.4.0] linux

## Reason and Possible fixes

If you know or suspect the reason for this bug, paste the code lines and suggest modifications.

## Checklist

- [*] I have checked that there is no similar issue in the repo (**required**)
- [*] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [*] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by vmoens** [comment]
Thanks for reporting
I can't reproduce this on main, can you try upgrading to the latest nightly?
Thanks!

**Comment by vmoens** [comment]
Now I have it
let me see what i can do :)
weird that the relevant PR did not catch it
