### ISSUE TITLE
[Feature Request] Support for sampling of random subsequences

### ISSUE THREAD

**Issue by nicklashansen** [pytorch/rl#905]
## Motivation

A variety of off-policy algorithms (both model-based and model-free) rely on sampling batches of random subsequences (i.e., not full trajectories nor single transitions) from the replay buffer. Examples of such algorithms are DrQ-v2 (https://arxiv.org/abs/2107.09645), Dreamer (https://arxiv.org/abs/1912.01603), and TD-MPC (https://arxiv.org/abs/2203.04955). Based on my initial experimentation with torchrl and tensordicts, I did not find an elegant way to implement such sampling. I am opening this issue to start a discussion on whether it would be feasible to add support for this, and -- if not -- whether it can be implemented more efficiently with existing components.

## Solution

Replay buffers typically store either transitions or trajectories. In the latter case, the most straightforward way to implement such a buffer seems to be with `TensorDict` objects and one of the available torchrl replay buffers.

In that case, each `TensorDict` has a `batch_size` of `(seq_len,)`. To sample a batch of subsequences, we currently have to first sample a batch of tensordicts which gives us a batch of size `(batch_size, seq_len,)`, and then slice random subsequences from each trajectory, i.e., along `dim=1`. Currently, `TensorDict` does not support `torch.gather` or similar functions, which means that we have to call `torch.gather` on individual items in the tensordict. It is unclear to me whether adding support for a `torch.gather`-like operation on tensordicts or a new replay buffer / sampler would be better from a design and cost perspective, but any such feature would greatly simplify implementations for this class of algorithms.

## Alternatives

My current implementation samples full trajectories and uses `torch.gather` to retrieve random subsequences for each item. The replay buffer is instantiated by
```
def make_buffer(cfg):
    """Create a replay buffer."""
    return ReplayBuffer(
    storage=LazyTensorStorage(
	    cfg.train_steps//cfg.episode_length,
	    device=torch.device('cuda'),
    ),
    sampler=RandomSampler(),
    )
```

and subsequences are retrieved by
```
def _sample(self, buffer):
    """Sample from a replay buffer and prepare batch."""
    td = buffer.sample(batch_size=self.cfg.batch_size)
    start_idx = torch.randint(0, td.shape[1]-self.cfg.horizon-1, (td.shape[0],))
    indices = (torch.arange(self.cfg.horizon+1) + start_idx.unsqueeze(-1)).unsqueeze(-1).to(td.device)
    obs, action, reward = td['obs'], td['action'], td['reward'].unsqueeze(-1)
    obs = torch.gather(
	    obs, dim=1, index=indices.repeat(1, 1, obs.shape[-1])
    ).permute(1,0,2).cuda(non_blocking=True)
    action = torch.gather(
	    action, dim=1, index=indices[:,:-1].repeat(1, 1, action.shape[-1])
    ).permute(1,0,2).cuda(non_blocking=True)
    reward = torch.gather(
	    reward, dim=1, index=indices[:,:-1]
    ).permute(1,0,2).cuda(non_blocking=True)
    obs, next_obses = obs[0], obs[1:]
    return obs, action, reward, next_obses
```

which is not very elegant and potentially also very costly if trajectories are >> than the subsequences. For example, DMControl trajectories are typically of length 500, whereas DrQ-v2 samples subsequences of length 3 and TD-MPC of length 5.

## Checklist

- [x] I have checked that there is no similar issue in the repo

**Comment by vmoens** [comment]
Hey that's a very valid request, and actually something we should have thought about before.
Good news is that we already have something like it but for trainers: first sample from the RB and then sample your sub-sequences.
have a look at it [here](https://github.com/pytorch/rl/blob/3902022c1ba39a486a6022789fa0a76c90d74134/torchrl/trainers/trainers.py#L939)

Assuming that you're not using prioritized RBs it should be fairly easy to port this to a sampler class for the replay buffers.

A few questions for you before I work on this:

- with `BatchSubSampler`, we were looking for a `"mask"` key that would represent what are the valid entries in your data. In some cases, you will be padding the items you store in your RB and it may be nice to make sure that the sampled subsequences are not polluted. I guess we'd like to keep that behaviour? Is `("collector", "mask")` and `"mask"` good keys to work with? (the first is the result of collecting data with `split_trajs=True` in your collector)
- We may approach this by coding this sampler as something to append to your sampler (composing samplers like we compose transforms). Another option would be to append this as a transform to your replay buffer!
I would lean towards this solution. Here's an example:
```python
rb = ReplayBuffer(storage=my_storage, sampler=my_sampler)
rb.append_transform(SubSequenceSampler(traj_len=60))
sample = rb.sample(128) # returns 128 sub-trajectories of length 60
```
That way we don't need to compose samplers, and we can just code a transform which could be re-used in other contexts.
Wdyt?
I can draft a PR today with this

**Comment by vmoens** [comment]
Here's the PR
https://github.com/pytorch/rl/pull/908

**Comment by nicklashansen** [comment]
That is a neat solution, thank you @vmoens!
