### ISSUE TITLE
to_numpy method of CompositeSpec does not work

### ISSUE THREAD

**Issue by ajlangley** [pytorch/rl#929]
## Describe the bug
The to_numpy method of `CompositeSpec` results in an error. The offending line seems to be in `torchrl/data/tensor_specs.py` in the `to_numpy` method of `CompositeTensorSpec`. Specifically, in the dictionary comprehension, the `_to_numpy` method of each of the child specs is being called. It does not appear, however, that `TensorSpec`s have a `_to_numpy` method.

## To Reproduce

```
import numpy as np

from torchrl.data import BoundedTensorSpec, CompositeSpec

from gymnasium import spaces

box1 = spaces.Box(low=np.zeros(2), high=np.ones(2))
box2 = spaces.Box(low=np.zeros(2), high=np.ones(2))
spec1 = BoundedTensorSpec(minimum=torch.zeros(2), maximum=torch.ones(2), dtype=torch.float32)
spec2 = BoundedTensorSpec(minimum=torch.zeros(2), maximum=torch.ones(2), dtype=torch.float32)
spec = CompositeSpec(x=spec1, y=spec2)

td = TensorDict({'x': torch.zeros(1, 2), 'y': torch.zeros(1, 2)}, batch_size=(1,))
spec.to_numpy(td)
```

## Reason and Possible fixes
Unless this breaks something that I'm not aware of, just changing `_to_numpy()` to `numpy()` resolves the issue.

## Checklist

- [ x  ] I have checked that there is no similar issue in the repo (**required**)
- [  x ] I have read the [documentation](https://github.com/pytorch/rl/tree/main/docs/) (**required**)
- [  x ] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by riiswa** [comment]
Hi, I'll have a look at what's going on and see if I can fix it!
