### ISSUE TITLE
BinaryDiscreteTensorSpec vs DiscreteTensorSpec

### ISSUE THREAD

**Issue by matteobettini** [pytorch/rl#980]
I recently saw that the default done_spec is
```python
 self.output_spec["done"] = DiscreteTensorSpec(
            n=2, shape=(*self.batch_size, 1), dtype=torch.bool, device=self.device
        )
```
Is there a reason that this is not a BinaryDiscreteTensorSpec?
Should we make BinaryDiscreteTensorSpec just call DiscreteTensorSpec with n=2 to simplify the codebase?

**Comment by vmoens** [comment]
I'm in for simplication yep.
We could inherit from `DiscreteTensorSpec` and put a warning saying that it will be deprecated some time in the future, wdyt?

**Comment by matteobettini** [comment]
Yep, even without deprecating it, but just using all the logic from  DiscreteTensorSpec
